{
	"Accounts":{
		"#path":[
			"https://www.zohoapis.com/crm/v2/Accounts"
		],
		"data<AccountData>[]":{
			"Owner":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Ownership":"VarChar(64)",
			"Description":"VarChar(175)",
			"$currency_symbol":"VarChar(64)",
			"Account_Type":"VarChar(64)",
			"Rating":"VarChar(64)",
			"SIC_Code":"VarChar(64)",
			"Shipping_State":"VarChar(64)",
			"$review_process":"VarChar(64)",
			"Website":"VarChar(64)",
			"Employees":"Integer",
			"Last_Activity_Time":"Timestamp(0)",
			"Industry":"VarChar(64)",
			"Record_Image":"VarChar(64)",
			"Modified_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$review":"VarChar(64)",
			"Account_Site":"VarChar(64)",
			"$process_flow":"Boolean",
			"Phone":"VarChar(64)",
			"Billing_Country":"VarChar(64)",
			"Account_Name":"VarChar(64)",
			"id":"BigInt",
			"Account_Number":"Integer",
			"$approved":"Boolean",
			"Ticker_Symbol":"VarChar(64)",
			"$approval":{
				"delegate":"Boolean",
				"approve":"Boolean",
				"reject":"Boolean",
				"resubmit":"Boolean"
			},
			"Modified_Time":"Timestamp(0)",
			"Billing_Street":"VarChar(64)",
			"Created_Time":"Timestamp(0)",
			"$editable":"Boolean",
			"Billing_Code":"Integer",
			"Parent_Account":"VarChar(64)",
			"Shipping_City":"VarChar(64)",
			"Shipping_Country":"VarChar(64)",
			"Shipping_Code":"VarChar(64)",
			"Billing_City":"VarChar(64)",
			"Billing_State":"VarChar(64)",
			"Tag":"JSON",
			"Created_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Fax":"VarChar(64)",
			"Annual_Revenue":"Integer",
			"Shipping_Street":"VarChar(64)"
		},
		"info":{
			"per_page":"Integer,#key",
			"count":"Integer",
			"page":"Integer",
			"more_records":"Boolean"
		}
	},
	"Leads":{
		"#path":[
			"https://www.zohoapis.com/crm/v2/Leads"
		],
		"data<LeadData>[]":{
			"Owner":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Company":"VarChar(64)",
			"Email":"VarChar(64)",
			"Description":"VarChar(64)",
			"$currency_symbol":"VarChar(64)",
			"Rating":"VarChar(64)",
			"$review_process":"VarChar(64)",
			"Website":"VarChar(64)",
			"Twitter":"VarChar(64)",
			"Salutation":"VarChar(64)",
			"Last_Activity_Time":"Timestamp(0)",
			"First_Name":"VarChar(64)",
			"Full_Name":"VarChar(64)",
			"Lead_Status":"VarChar(64)",
			"Industry":"VarChar(64)",
			"Record_Image":"VarChar(64)",
			"Modified_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$review":"VarChar(64)",
			"Skype_ID":"VarChar(64)",
			"$converted":"Boolean",
			"$process_flow":"Boolean",
			"Phone":"VarChar(64)",
			"Street":"VarChar(64)",
			"Zip_Code":"Integer",
			"id":"BigInt",
			"Email_Opt_Out":"Boolean",
			"$approved":"Boolean",
			"Designation":"VarChar(64)",
			"$approval":{
				"delegate":"Boolean",
				"approve":"Boolean",
				"reject":"Boolean",
				"resubmit":"Boolean"
			},
			"Modified_Time":"Timestamp(0)",
			"Created_Time":"Timestamp(0)",
			"$converted_detail":"JSON",
			"$editable":"Boolean",
			"City":"VarChar(64)",
			"No_of_Employees":"VarChar(64)",
			"Mobile":"VarChar(64)",
			"Last_Name":"VarChar(64)",
			"State":"VarChar(64)",
			"Lead_Source":"VarChar(64)",
			"Country":"VarChar(64)",
			"Tag":"JSON",
			"Created_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Fax":"VarChar(64)",
			"Annual_Revenue":"Integer",
			"Secondary_Email":"VarChar(64)"
		},
		"info":{
			"per_page":"Integer,#key",
			"count":"Integer",
			"page":"Integer",
			"more_records":"Boolean"
		}
	},
	"Contacts":{
		"#path":[
			"https://www.zohoapis.com/crm/v2/Contacts"
		],
		"data<ContactData>[]":{
			"Owner":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Email":"VarChar(64)",
			"$currency_symbol":"VarChar(64)",
			"Other_Phone":"VarChar(64)",
			"Mailing_State":"VarChar(64)",
			"Other_State":"VarChar(64)",
			"Other_Country":"VarChar(64)",
			"Last_Activity_Time":"Timestamp(0)",
			"Department":"VarChar(64)",
			"$process_flow":"Boolean",
			"Assistant":"VarChar(64)",
			"Mailing_Country":"VarChar(64)",
			"id":"BigInt",
			"$approved":"Boolean",
			"Reporting_To":"VarChar(64)",
			"$approval":{
				"delegate":"Boolean",
				"approve":"Boolean",
				"reject":"Boolean",
				"resubmit":"Boolean"
			},
			"Other_City":"VarChar(64)",
			"Created_Time":"Timestamp(0)",
			"$editable":"Boolean",
			"Home_Phone":"VarChar(64)",
			"Created_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Secondary_Email":"VarChar(64)",
			"Description":"VarChar(64)",
			"Vendor_Name":"VarChar(64)",
			"Mailing_Zip":"Integer",
			"$review_process":"VarChar(64)",
			"Twitter":"VarChar(64)",
			"Other_Zip":"VarChar(64)",
			"Mailing_Street":"VarChar(64)",
			"Salutation":"VarChar(64)",
			"First_Name":"VarChar(64)",
			"Full_Name":"VarChar(64)",
			"Asst_Phone":"VarChar(64)",
			"Record_Image":"VarChar(64)",
			"Modified_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$review":"VarChar(64)",
			"Skype_ID":"VarChar(64)",
			"Phone":"VarChar(64)",
			"Account_Name":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Email_Opt_Out":"Boolean",
			"Modified_Time":"Timestamp(0)",
			"Date_of_Birth":"VarChar(64)",
			"Mailing_City":"VarChar(64)",
			"Title":"VarChar(64)",
			"Other_Street":"VarChar(64)",
			"Mobile":"VarChar(64)",
			"Last_Name":"VarChar(64)",
			"Lead_Source":"VarChar(64)",
			"Tag":"JSON",
			"Fax":"VarChar(64)"
		},
		"info":{
			"per_page":"Integer,#key",
			"count":"Integer",
			"page":"Integer",
			"more_records":"Boolean"
		}
	},
	"Deals":{
		"#path":[
			"https://www.zohoapis.com/crm/v2/Deals"
		],
		"data<DealsData>[]":{
			"Owner":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Description":"VarChar(64)",
			"$currency_symbol":"VarChar(64)",
			"Campaign_Source":"VarChar(64)",
			"$review_process":"VarChar(64)",
			"$followers":"VarChar(64)",
			"Closing_Date":"Date",
			"Last_Activity_Time":"Timestamp(0)",
			"Modified_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$review":"VarChar(64)",
			"Lead_Conversion_Time":"VarChar(64)",
			"$process_flow":"Boolean",
			"Deal_Name":"VarChar(64)",
			"Expected_Revenue":"Integer",
			"Overall_Sales_Duration":"Integer",
			"Stage":"VarChar(64)",
			"Account_Name":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"id":"BigInt",
			"$approved":"Boolean",
			"$approval":{
				"delegate":"Boolean",
				"approve":"Boolean",
				"reject":"Boolean",
				"resubmit":"Boolean"
			},
			"Modified_Time":"Timestamp(0)",
			"Created_Time":"Timestamp(0)",
			"Amount":"Integer",
			"$followed":"Boolean",
			"Probability":"Integer",
			"Next_Step":"VarChar(64)",
			"$editable":"Boolean",
			"Contact_Name":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Sales_Cycle_Duration":"Integer",
			"Type":"VarChar(64)",
			"Lead_Source":"VarChar(64)",
			"Created_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Tag":"JSON"
		},
		"info":{
			"per_page":"Integer,#key",
			"count":"Integer",
			"page":"Integer",
			"more_records":"Boolean"
		}
	},
	"Events":{
		"#path":[
			"https://www.zohoapis.com/crm/v2/Events"
		],
		"data<EventsData>[]":{
			"All_day":"Boolean",
			"Owner":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Check_In_State":"VarChar(64)",
			"Check_In_Address":"VarChar(64)",
			"Description":"VarChar(64)",
			"$currency_symbol":"VarChar(64)",
			"Start_DateTime":"Timestamp(0)",
			"$review_process":"VarChar(64)",
			"Latitude":"VarChar(64)",
			"Participants":"JSON",
			"Event_Title":"VarChar(64)",
			"$calendar_booking_event":"Boolean",
			"End_DateTime":"Timestamp(0)",
			"Check_In_By":"VarChar(64)",
			"Modified_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$review":"VarChar(64)",
			"$process_flow":"Boolean",
			"Check_In_City":"VarChar(64)",
			"id":"BigInt",
			"Check_In_Comment":"VarChar(64)",
			"$approved":"Boolean",
			"Remind_At":"VarChar(64)",
			"Who_Id":"VarChar(64)",
			"Check_In_Status":"VarChar(64)",
			"Check_In_Country":"VarChar(64)",
			"$approval":{
				"delegate":"Boolean",
				"approve":"Boolean",
				"reject":"Boolean",
				"resubmit":"Boolean"
			},
			"Modified_Time":"Timestamp(0)",
			"Venue":"VarChar(64)",
			"ZIP_Code":"VarChar(64)",
			"Created_Time":"Timestamp(0)",
			"$editable":"Boolean",
			"$recurrence_id":"BigInt",
			"Longitude":"VarChar(64)",
			"Check_In_Time":"VarChar(64)",
			"$se_module":"VarChar(64)",
			"Recurring_Activity":"VarChar(64)",
			"What_Id":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Check_In_Sub_Locality":"VarChar(64)",
			"$u_id":"BigInt",
			"Created_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Tag":"JSON",
			"$send_notification":"Boolean"
		},
		"info":{
			"per_page":"Integer,#key",
			"count":"Integer",
			"page":"Integer",
			"more_records":"Boolean"
		}
	},
	"Calls":{
		"#path":[
			"https://www.zohoapis.com/crm/v2/Calls"
		],
		"data<CallsData>[]":{
			"Call_Duration":"VarChar(64)",
			"Owner":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Description":"VarChar(64)",
			"$currency_symbol":"VarChar(64)",
			"$calendar_booking_call":"Boolean",
			"$review_process":"VarChar(64)",
			"Modified_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$review":"VarChar(64)",
			"$process_flow":"Boolean",
			"Call_Purpose":"VarChar(64)",
			"id":"BigInt",
			"Call_Status":"VarChar(64)",
			"$approved":"Boolean",
			"Who_Id":"VarChar(64)",
			"$approval":{
				"delegate":"Boolean",
				"approve":"Boolean",
				"reject":"Boolean",
				"resubmit":"Boolean"
			},
			"Modified_Time":"Timestamp(0)",
			"Reminder":"Timestamp(0)",
			"Created_Time":"Timestamp(0)",
			"Call_Start_Time":"Timestamp(0)",
			"$editable":"Boolean",
			"Subject":"VarChar(64)",
			"$se_module":"VarChar(64)",
			"Call_Type":"VarChar(64)",
			"Call_Result":"VarChar(64)",
			"What_Id":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Call_Duration_in_seconds":"VarChar(64)",
			"Created_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Tag":"JSON"
		},
		"info":{
			"per_page":"Integer,#key",
			"count":"Integer",
			"page":"Integer",
			"more_records":"Boolean"
		}
	},
	"Products":{
		"#path":[
			"https://www.zohoapis.com/crm/v2/Products"
		],
		"data<ProductsData>[]":{
			"Qty_in_Demand":"Integer",
			"Owner":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$currency_symbol":"VarChar(64)",
			"Sales_Start_Date":"VarChar(64)",
			"Tax[1]":"VarChar(64)",
			"Product_Active":"Boolean",
			"Regular_price":"Double",
			"Meta_wpcom_is_markdown":"Integer",
			"Upsells":"VarChar(64)",
			"$process_flow":"Boolean",
			"Length_in":"Integer",
			"Download_expiry_days":"Integer",
			"Attribute_1_value_s":"VarChar(64)",
			"Manufacturer":"VarChar(64)",
			"id":"BigInt",
			"Download_1_URL":"VarChar(127)",
			"$approved":"Boolean",
			"Shipping_class":"VarChar(64)",
			"$approval":{
				"delegate":"Boolean",
				"approve":"Boolean",
				"reject":"Boolean",
				"resubmit":"Boolean"
			},
			"Short_description":"VarChar(64)",
			"Categories":"VarChar(64)",
			"Position":"Integer",
			"Created_Time":"Timestamp(0)",
			"Images":"VarChar(382)",
			"Product_Name":"VarChar(64)",
			"Handler":"VarChar(64)",
			"$taxable":"Boolean",
			"$editable":"Boolean",
			"Height_in":"Double",
			"Support_Start_Date":"VarChar(64)",
			"Attribute_2_visible":"Integer",
			"Grouped_products":"VarChar(66)",
			"Tax_class":"VarChar(64)",
			"Download_1_name":"VarChar(64)",
			"Allow_customer_reviews":"Boolean",
			"Created_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Taxable":"Boolean",
			"Product_Category":"VarChar(64)",
			"Attribute_1_global":"Integer",
			"Crosssells":"VarChar(64)",
			"Description":"VarChar(901)",
			"Vendor_Name":"VarChar(64)",
			"Parent":"VarChar(64)",
			"Is_featured":"Boolean",
			"Attribute_2_global":"Integer",
			"$review_process":"VarChar(64)",
			"Attribute_2_name":"VarChar(64)",
			"External_URL":"VarChar(88)",
			"Record_Image":"VarChar(64)",
			"Date_sale_price_ends":"VarChar(64)",
			"Modified_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$review":"VarChar(64)",
			"Product_Code":"VarChar(64)",
			"Sold_individually":"Boolean",
			"In_stock":"Boolean",
			"Support_Expiry_Date":"VarChar(64)",
			"Visibility_in_catalog":"VarChar(64)",
			"Attribute_2_value_s":"VarChar(64)",
			"Download_limit":"Integer",
			"Attribute_1_name":"VarChar(64)",
			"Modified_Time":"Timestamp(0)",
			"Date_sale_price_starts":"VarChar(64)",
			"Purchase_note":"VarChar(64)",
			"Attribute_1_visible":"Integer",
			"Commission_Rate":"VarChar(64)",
			"Download_2_URL":"VarChar(126)",
			"Weight_lbs":"Double",
			"Button_text":"VarChar(64)",
			"Type":"VarChar(64)",
			"Width_in":"Double",
			"Usage_Unit":"VarChar(64)",
			"Qty_Ordered":"Integer",
			"ID1":"Integer",
			"Download_2_name":"VarChar(64)",
			"Published":"Boolean",
			"Qty_in_Stock":"Integer",
			"Tag":"JSON",
			"SKU":"VarChar(64)",
			"Backorders_allowed":"Boolean",
			"Sales_End_Date":"VarChar(64)",
			"Sale_price":"Integer",
			"Unit_Price":"VarChar(64)",
			"Reorder_Level":"Integer"
		},
		"info":{
			"per_page":"Integer,#key",
			"count":"Integer",
			"page":"Integer",
			"more_records":"Boolean"
		}
	},
	"Vendors":{
		"#path":[
			"https://www.zohoapis.com/crm/v2/Vendors"
		],
		"data<VendorsData>[]":{
			"Owner":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Email":"VarChar(64)",
			"Category":"VarChar(64)",
			"Description":"VarChar(64)",
			"$currency_symbol":"VarChar(64)",
			"Vendor_Name":"VarChar(64)",
			"$review_process":"VarChar(64)",
			"Website":"VarChar(64)",
			"Record_Image":"VarChar(64)",
			"Modified_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$review":"VarChar(64)",
			"$process_flow":"Boolean",
			"Phone":"BigInt",
			"Street":"VarChar(64)",
			"Zip_Code":"VarChar(64)",
			"id":"BigInt",
			"$approved":"Boolean",
			"$approval":{
				"delegate":"Boolean",
				"approve":"Boolean",
				"reject":"Boolean",
				"resubmit":"Boolean"
			},
			"Modified_Time":"Timestamp(0)",
			"Created_Time":"Timestamp(0)",
			"$editable":"Boolean",
			"City":"VarChar(64)",
			"State":"VarChar(64)",
			"GL_Account":"VarChar(64)",
			"Country":"VarChar(64)",
			"Created_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Tag":"JSON"
		},
		"info":{
			"per_page":"Integer,#key",
			"count":"Integer",
			"page":"Integer",
			"more_records":"Boolean"
		}
	},
	"Notes":{
		"#path":[
			"https://www.zohoapis.com/crm/v2/Notes"
		],
		"data<NotesData>[]":{
			"Owner":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Modified_Time":"Timestamp(0)",
			"$attachments":"VarChar(64)",
			"Created_Time":"Timestamp(0)",
			"Parent_Id":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$editable":"Boolean",
			"$se_module":"VarChar(64)",
			"Modified_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$size":"VarChar(64)",
			"$voice_note":"Boolean",
			"id":"BigInt",
			"Created_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Note_Title":"VarChar(64)",
			"Note_Content":"VarChar(102)"
		},
		"info":{
			"per_page":"Integer,#key",
			"count":"Integer",
			"page":"Integer",
			"more_records":"Boolean"
		}
	},
	"Activities":{
		"#path":[
			"https://www.zohoapis.com/crm/v2/Activities"
		],
		"data<ActivitiesData>[]":{
			"All_day":"Boolean",
			"Check_In_State":"VarChar(64)",
			"Owner":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$currency_symbol":"VarChar(64)",
			"Latitude":"VarChar(64)",
			"Participants":"JSON",
			"$process_flow":"Boolean",
			"Check_In_City":"VarChar(64)",
			"Call_Purpose":"VarChar(64)",
			"id":"BigInt",
			"Check_In_Comment":"VarChar(64)",
			"$approved":"Boolean",
			"Check_In_Status":"VarChar(64)",
			"Who_Id":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Status":"VarChar(64)",
			"$approval":{
				"delegate":"Boolean",
				"approve":"Boolean",
				"reject":"Boolean",
				"resubmit":"Boolean"
			},
			"Venue":"VarChar(64)",
			"ZIP_Code":"VarChar(64)",
			"Activity_Type":"VarChar(64)",
			"Priority":"VarChar(64)",
			"Created_Time":"Timestamp(0)",
			"Call_Start_Time":"Timestamp(0)",
			"$editable":"Boolean",
			"Longitude":"VarChar(64)",
			"Check_In_Time":"VarChar(64)",
			"Call_Result":"VarChar(64)",
			"Recurring_Activity":"VarChar(64)",
			"What_Id":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Created_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"Call_Duration":"VarChar(64)",
			"Check_In_Address":"VarChar(64)",
			"Description":"VarChar(81)",
			"Closed_Time":"Timestamp(0)",
			"Start_DateTime":"Timestamp(0)",
			"$review_process":"VarChar(64)",
			"End_DateTime":"Timestamp(0)",
			"Check_In_By":"VarChar(64)",
			"Modified_By":{
				"name":"VarChar(64)",
				"id":"BigInt"
			},
			"$review":"VarChar(64)",
			"Call_Status":"VarChar(64)",
			"Check_In_Country":"VarChar(64)",
			"Modified_Time":"Timestamp(0)",
			"Reminder":"Timestamp(0)",
			"Due_Date":"Date",
			"Subject":"VarChar(64)",
			"$se_module":"VarChar(64)",
			"Call_Type":"VarChar(64)",
			"Check_In_Sub_Locality":"VarChar(64)",
			"Call_Duration_in_seconds":"VarChar(64)",
			"Tag":"JSON"
		},
		"info":{
			"per_page":"Integer,#key",
			"count":"Integer",
			"page":"Integer",
			"more_records":"Boolean"
		}
	}
}