{
	"Companies":{
		"#path":[
			"https://api.hubapi.com/companies/v2/companies/paged"
		],
		"has-more":"Boolean",
		"offset":"BigInt,#key",
		"companies[]":{
			"portalId":"Integer",
			"companyId":"BigInt",
			"isDeleted":"Boolean",
			"properties":"JSON",
			"additionalDomains":"JSON",
			"stateChanges":"JSON",
			"mergeAudits":"JSON"
		}
	},
	"CompanyProperties":{
		"#path":[
			"https://api.hubapi.com/properties/v1/companies/properties"
		],
		"name":"VarChar(66)",
		"label":"VarChar(46),#key",
		"description":"VarChar(373)",
		"groupName":"VarChar(33)",
		"type":"VarChar(16)",
		"fieldType":"VarChar(22)",
		"deleted":"VarChar(64)",
		"createdAt":"VarChar(64)",
		"formField":"Boolean",
		"displayOrder":"Integer",
		"readOnlyValue":"Boolean",
		"readOnlyDefinition":"Boolean",
		"mutableDefinitionNotDeletable":"Boolean",
		"favorited":"Boolean",
		"favoritedOrder":"Integer",
		"calculated":"Boolean",
		"externalOptions":"Boolean",
		"displayMode":"VarChar(19)",
		"showCurrencySymbol":"Boolean",
		"hubspotDefined":"Boolean",
		"hidden":"Boolean",
		"updatedAt":"VarChar(64)",
		"referencedObjectType":"VarChar(64)",
		"hasUniqueValue":"Boolean",
		"optionSortStrategy":"VarChar(64)",
		"createdUserId":"VarChar(64)",
		"searchableInGlobalSearch":"Boolean",
		"currencyPropertyName":"VarChar(64)",
		"textDisplayHint":"VarChar(64)",
		"numberDisplayHint":"VarChar(64)",
		"optionsAreMutable":"Boolean",
		"isCustomizedDefault":"Boolean",
		"searchTextAnalysisMode":"VarChar(64)",
		"updatedUserId":"VarChar(64)",
		"options[]":{
			"label":"LongVarChar(4000)",
			"displayOrder":"Integer",
			"hidden":"Boolean",
			"readOnly":"Boolean",
			"doubleData":"VarChar(64)",
			"description":"VarChar(64)",
			"value":"VarChar(57)"
		}
	},
	"Contacts":{
		"#path":[
			"https://api.hubapi.com/contacts/v1/lists/all/contacts/all"
		],
		"contacts[]":{
			"addedAt":"BigInt",
			"vid":"Integer",
			"canonical-vid":"Integer",
			"merged-vids":"JSON",
			"portal-id":"Integer",
			"is-contact":"Boolean",
			"profile-token":"VarChar(210)",
			"profile-url":"VarChar(78)",
			"properties":{
				"firstname":{
					"value":"VarChar(64)"
				},
				"lastmodifieddate":{
					"value":"BigInt"
				},
				"company":{
					"value":"VarChar(64)"
				},
				"lastname":{
					"value":"VarChar(64)"
				}
			},
			"form-submissions":"JSON",
			"identity-profiles[1]":{
				"vid":"Integer",
				"saved-at-timestamp":"BigInt",
				"deleted-changed-timestamp":"Integer",
				"identities[2]":{
					"type":"VarChar(13)",
					"value":"VarChar(64)",
					"timestamp":"BigInt",
					"is-primary":"Boolean"
				}
			},
			"merge-audits":"JSON"
		},
		"has-more":"Boolean",
		"vid-offset":"Integer,#key"
	},
	"ContactsLists":{
		"#path":[
			"https://api.hubapi.com/contacts/v1/lists"
		],
		"lists[]":{
			"teamIds":"JSON",
			"portalId":"Integer",
			"createdAt":"BigInt",
			"listId":"Integer",
			"metaData":{
				"listReferencesCount":"VarChar(64)",
				"parentFolderId":"VarChar(64)",
				"processing":"VarChar(64)",
				"lastProcessingStateChangeAt":"BigInt",
				"error":"VarChar(64)",
				"lastSizeChangeAt":"BigInt",
				"size":"Integer"
			},
			"authorId":"Integer",
			"listType":"VarChar(64)",
			"archived":"Boolean",
			"dynamic":"Boolean",
			"internalListId":"Integer",
			"updatedAt":"BigInt",
			"filters":"JSON",
			"name":"VarChar(64)"
		},
		"offset":"Integer,#key",
		"has-more":"Boolean"
	},
	"ContactProperties":{
		"#path":[
			"https://api.hubapi.com/properties/v1/contacts/properties"
		],
		"name":"VarChar(78)",
		"label":"VarChar(88)",
		"description":"VarChar(283)",
		"groupName":"VarChar(31),#key",
		"type":"VarChar(18)",
		"fieldType":"VarChar(31)",
		"deleted":"Boolean",
		"createdAt":"BigInt",
		"formField":"Boolean",
		"displayOrder":"Integer",
		"readOnlyValue":"Boolean",
		"readOnlyDefinition":"Boolean",
		"mutableDefinitionNotDeletable":"Boolean",
		"favorited":"Boolean",
		"favoritedOrder":"Integer",
		"calculated":"Boolean",
		"externalOptions":"Boolean",
		"displayMode":"VarChar(19)",
		"showCurrencySymbol":"Boolean",
		"hubspotDefined":"Boolean",
		"hidden":"Boolean",
		"updatedAt":"BigInt",
		"optionSortStrategy":"VarChar(64)",
		"createdUserId":"VarChar(64)",
		"referencedObjectType":"VarChar(64)",
		"searchableInGlobalSearch":"Boolean",
		"hasUniqueValue":"Boolean",
		"currencyPropertyName":"VarChar(64)",
		"textDisplayHint":"VarChar(64)",
		"numberDisplayHint":"VarChar(64)",
		"optionsAreMutable":"Boolean",
		"isCustomizedDefault":"Boolean",
		"searchTextAnalysisMode":"VarChar(64)",
		"updatedUserId":"VarChar(64)",
		"options[]":{
			"label":"VarChar(61)",
			"displayOrder":"Integer",
			"hidden":"Boolean",
			"readOnly":"Boolean",
			"doubleData":"VarChar(64)",
			"description":"VarChar(64)",
			"value":"VarChar(61)"
		}
	},
	"Deals":{
		"#path":[
			"https://api.hubapi.com/deals/v1/deal/paged"
		],
		"deals[]":{
			"portalId":"Integer",
			"dealId":"Integer",
			"isDeleted":"Boolean",
			"associations":"VarChar(64)",
			"properties":{
				"hs_object_id":{
					"value":"Integer",
					"timestamp":"Integer",
					"source":"VarChar(15)",
					"sourceId":"VarChar(64)",
					"versions[1]":{
						"name":"VarChar(18)",
						"value":"Integer",
						"source":"VarChar(15)",
						"sourceVid":"JSON"
					}
				}
			},
			"imports":"JSON",
			"stateChanges":"JSON"
		},
		"hasMore":"Boolean",
		"offset":"Integer,#key"
	},
	"DealProperties":{
		"#path":[
			"https://api.hubapi.com/properties/v1/deals/properties"
		],
		"name":"VarChar(60)",
		"label":"VarChar(51),#key",
		"description":"VarChar(465)",
		"groupName":"VarChar(30)",
		"type":"VarChar(16)",
		"fieldType":"VarChar(30)",
		"deleted":"VarChar(64)",
		"createdAt":"VarChar(64)",
		"currencyPropertyName":"VarChar(64)",
		"formField":"Boolean",
		"displayOrder":"Integer",
		"readOnlyValue":"Boolean",
		"readOnlyDefinition":"Boolean",
		"mutableDefinitionNotDeletable":"Boolean",
		"favorited":"Boolean",
		"favoritedOrder":"Integer",
		"calculated":"Boolean",
		"externalOptions":"Boolean",
		"displayMode":"VarChar(19)",
		"showCurrencySymbol":"Boolean",
		"hubspotDefined":"Boolean",
		"hidden":"Boolean",
		"updatedAt":"VarChar(64)",
		"referencedObjectType":"VarChar(64)",
		"hasUniqueValue":"Boolean",
		"createdUserId":"VarChar(64)",
		"searchableInGlobalSearch":"Boolean",
		"optionSortStrategy":"VarChar(64)",
		"textDisplayHint":"VarChar(64)",
		"searchTextAnalysisMode":"VarChar(64)",
		"optionsAreMutable":"Boolean",
		"numberDisplayHint":"VarChar(64)",
		"isCustomizedDefault":"Boolean",
		"updatedUserId":"VarChar(64)",
		"options[]":{
			"readOnly":"VarChar(64)",
			"label":"VarChar(64)",
			"displayOrder":"Integer",
			"hidden":"Boolean",
			"doubleData":"VarChar(64)",
			"description":"VarChar(64)",
			"value":"VarChar(64)"
		}
	},
	"DealPipelines":{
		"#path":[
			"https://api.hubapi.com/deals/v1/pipelines"
		],
		"pipelineId":"VarChar(64),#key",
		"stages[]":{
			"stageId":"VarChar(64)",
			"label":"VarChar(64)",
			"probability":"Double",
			"active":"Boolean",
			"displayOrder":"Integer",
			"closedWon":"Boolean"
		},
		"label":"VarChar(64)",
		"active":"Boolean",
		"displayOrder":"Integer",
		"staticDefault":"Boolean"
	},
	"Engagement":{
		"#path":[
			"https://api.hubapi.com/engagements/v1/engagements/paged"
		],
		"results[]":{
			"engagement":{
				"id":"BigInt",
				"portalId":"Integer",
				"active":"Boolean",
				"createdAt":"BigInt",
				"lastUpdated":"BigInt",
				"createdBy":"Integer",
				"modifiedBy":"Integer",
				"ownerId":"Integer",
				"type":"VarChar(64)",
				"timestamp":"BigInt",
				"teamId":"Integer",
				"allAccessibleTeamIds[1]":"Integer",
				"queueMembershipIds":"JSON",
				"bodyPreview":"VarChar(64)",
				"bodyPreviewIsTruncated":"Boolean",
				"bodyPreviewHtml":"VarChar(102)"
			},
			"associations":{
				"contactIds":"JSON",
				"companyIds[]":"BigInt",
				"dealIds":"JSON",
				"ownerIds":"JSON",
				"workflowIds":"JSON",
				"ticketIds":"JSON",
				"contentIds":"JSON",
				"quoteIds":"JSON"
			},
			"attachments":"JSON",
			"scheduledTasks[]":{
				"engagementId":"BigInt",
				"portalId":"Integer",
				"engagementType":"VarChar(64)",
				"taskType":"VarChar(64)",
				"timestamp":"BigInt",
				"uuid":"VarChar(64)"
			},
			"metadata":{
				"status":"VarChar(64)",
				"subject":"VarChar(64)",
				"taskType":"VarChar(64)",
				"reminders[]":"BigInt",
				"sendDefaultReminder":"Boolean",
				"body":"VarChar(64)",
				"unknownVisitorConversation":"Boolean"
			}
		},
		"hasMore":"Boolean",
		"offset":"BigInt,#key"
	},
	"Forms":{
		"#path":[
			"https://api.hubapi.com/forms/v2/forms"
		],
		"portalId":"Integer,#key",
		"guid":"GUID",
		"name":"VarChar(88)",
		"action":"VarChar(64)",
		"method":"VarChar(64)",
		"cssClass":"VarChar(64)",
		"redirect":"VarChar(64)",
		"submitText":"VarChar(64)",
		"followUpId":"VarChar(64)",
		"notifyRecipients":"VarChar(64)",
		"leadNurturingCampaignId":"VarChar(64)",
		"formFieldGroups[]":{
			"fields[]":{
				"name":"VarChar(75)",
				"label":"VarChar(64)",
				"type":"VarChar(64)",
				"fieldType":"VarChar(64)",
				"description":"VarChar(64)",
				"groupName":"VarChar(64)",
				"displayOrder":"Integer",
				"required":"Boolean",
				"selectedOptions[]":"VarChar(64)",
				"options[]":{
					"label":"VarChar(64)",
					"value":"VarChar(64)",
					"displayOrder":"Integer",
					"doubleData":"Double",
					"hidden":"Boolean",
					"description":"VarChar(64)",
					"readOnly":"Boolean"
				},
				"validation":{
					"name":"VarChar(64)",
					"message":"VarChar(64)",
					"data":"VarChar(64)",
					"useDefaultBlockList":"Boolean",
					"blockedEmailAddresses":"JSON"
				},
				"enabled":"Boolean",
				"hidden":"Boolean",
				"defaultValue":"VarChar(64)",
				"isSmartField":"Boolean",
				"unselectedLabel":"VarChar(64)",
				"placeholder":"VarChar(64)",
				"dependentFieldFilters":"JSON",
				"labelHidden":"Boolean",
				"propertyObjectType":"VarChar(64)",
				"metaData":"JSON"
			},
			"default":"Boolean",
			"isSmartGroup":"Boolean",
			"richText":{
				"content":"VarChar(64)"
			}
		},
		"createdAt":"BigInt",
		"updatedAt":"BigInt",
		"performableHtml":"VarChar(64)",
		"migratedFrom":"VarChar(64)",
		"ignoreCurrentValues":"Boolean",
		"metaData":"JSON",
		"deletable":"Boolean",
		"inlineMessage":"VarChar(64)",
		"tmsId":"VarChar(64)",
		"captchaEnabled":"Boolean",
		"campaignGuid":"VarChar(64)",
		"cloneable":"Boolean",
		"editable":"Boolean",
		"formType":"VarChar(64)",
		"deletedAt":"Integer",
		"themeName":"VarChar(64)",
		"parentId":"Integer",
		"style":"VarChar(64)",
		"isPublished":"Boolean",
		"publishAt":"Integer",
		"unpublishAt":"Integer",
		"publishedAt":"Integer",
		"multivariateTest":{
			"variants":"JSON",
			"startAtTimestamp":"Integer",
			"endAtTimestamp":"Integer",
			"winningVariantId":"VarChar(64)",
			"finished":"Boolean",
			"controlId":"VarChar(64)"
		},
		"kickbackEmailWorkflowId":"Integer",
		"kickbackEmailsJson":"VarChar(64)"
	},
	"Owners":{
		"#path":[
			"https://api.hubapi.com/owners/v2/owners"
		],
		"portalId":"Integer,#key",
		"ownerId":"Integer",
		"type":"VarChar(9)",
		"firstName":"VarChar(64)",
		"lastName":"VarChar(64)",
		"email":"VarChar(76)",
		"createdAt":"BigInt",
		"updatedAt":"BigInt",
		"remoteList[1]":{
			"id":"Integer",
			"portalId":"Integer",
			"ownerId":"Integer",
			"remoteId":"Integer",
			"remoteType":"VarChar(10)",
			"active":"Boolean"
		},
		"hasContactsAccess":"Boolean",
		"activeUserId":"Integer",
		"userIdIncludingInactive":"Integer",
		"isActive":"Boolean"
	},
	"Products":{
		"#path":[
			"https://api.hubapi.com/crm-objects/v1/objects/products/paged"
		],
		"status":"VarChar(64),#key",
		"message":"VarChar(69)",
		"correlationId":"GUID",
		"requestId":"GUID"
	},
	"Tickets":{
		"#path":[
			"https://api.hubapi.com/crm-objects/v1/objects/tickets/paged"
		],
		"objects[]":{
			"objectType":"VarChar(64)",
			"portalId":"Integer",
			"objectId":"Integer",
			"properties":"JSON",
			"isDeleted":"Boolean"
		},
		"hasMore":"Boolean",
		"offset":"Integer,#key"
	},
	"Emails":{
		"#path":[
			"https://api.hubapi.com/marketing-emails/v1/emails"
		],
		"limit":"Integer,#key",
		"objects[]":{
			"ab":"Boolean",
			"abHoursToWait":"Integer",
			"abSampleSizeDefault":"VarChar(64)",
			"abSamplingDefault":"VarChar(64)",
			"abSuccessMetric":"VarChar(64)",
			"abTestPercentage":"Integer",
			"abVariation":"Boolean",
			"absoluteUrl":"VarChar(120)",
			"allEmailCampaignIds[]":"Integer",
			"analyticsPageId":"BigInt",
			"analyticsPageType":"VarChar(64)",
			"archived":"Boolean",
			"authorAt":"BigInt",
			"blogRssSettings":"VarChar(64)",
			"canSpamSettingsId":"BigInt",
			"categoryId":"Integer",
			"contentAccessRuleIds":"JSON",
			"contentTypeCategory":"Integer",
			"createPage":"Boolean",
			"created":"BigInt",
			"currentState":"VarChar(64)",
			"currentlyPublished":"Boolean",
			"customReplyTo":"VarChar(64)",
			"customReplyToEnabled":"Boolean",
			"domain":"VarChar(64)",
			"emailBody":"VarChar(130)",
			"emailCampaignGroupId":"Integer",
			"emailNote":"VarChar(64)",
			"emailTemplateMode":"VarChar(64)",
			"emailType":"VarChar(64)",
			"feedbackEmailCategory":"VarChar(64)",
			"feedbackSurveyId":"Integer",
			"flexAreas":{
				"main":{
					"boxFirstElementIndex":"Integer",
					"boxLastElementIndex":"Integer",
					"boxed":"Boolean",
					"isSingleColumnFullWidth":"Boolean",
					"sections[]":{
						"columns[]":{
							"id":"VarChar(64)",
							"widgets[]":"VarChar(64)",
							"width":"Integer"
						},
						"id":"VarChar(64)",
						"style":{
							"backgroundColor":"VarChar(64)",
							"backgroundType":"VarChar(64)",
							"paddingBottom":"VarChar(64)",
							"paddingTop":"VarChar(64)"
						}
					}
				}
			},
			"freezeDate":"BigInt",
			"fromName":"VarChar(64)",
			"hasContentAccessRules":"Boolean",
			"htmlTitle":"VarChar(64)",
			"id":"BigInt",
			"isGraymailSuppressionEnabled":"Boolean",
			"isLocalTimezoneSend":"Boolean",
			"isPublished":"Boolean",
			"isRecipientFatigueSuppressionEnabled":"VarChar(64)",
			"layoutSections":"JSON",
			"leadFlowId":"VarChar(64)",
			"liveDomain":"VarChar(64)",
			"mailingListsExcluded":"JSON",
			"mailingListsIncluded":"JSON",
			"maxRssEntries":"Integer",
			"metaDescription":"VarChar(64)",
			"name":"VarChar(64)",
			"pageExpiryEnabled":"Boolean",
			"pageRedirected":"Boolean",
			"pastMabExperimentIds":"JSON",
			"portalId":"Integer",
			"previewKey":"VarChar(64)",
			"primaryEmailCampaignId":"Integer",
			"processingStatus":"VarChar(64)",
			"publishDate":"BigInt",
			"publishedAt":"BigInt",
			"publishedUrl":"VarChar(120)",
			"replyTo":"VarChar(64)",
			"resolvedDomain":"VarChar(64)",
			"rssEmailByText":"VarChar(64)",
			"rssEmailClickThroughText":"VarChar(64)",
			"rssEmailCommentText":"VarChar(64)",
			"rssEmailEntryTemplateEnabled":"Boolean",
			"rssEmailImageMaxWidth":"Integer",
			"rssEmailUrl":"VarChar(64)",
			"slug":"VarChar(78)",
			"smartEmailFields":"JSON",
			"state":"VarChar(64)",
			"styleSettings":{
				"background_color":"VarChar(64)",
				"background_image":"VarChar(64)",
				"background_image_type":"VarChar(64)",
				"body_border_color":"VarChar(64)",
				"body_border_color_choice":"VarChar(64)",
				"body_border_width":"Integer",
				"body_color":"VarChar(64)",
				"color_picker_favorite1":"VarChar(64)",
				"color_picker_favorite2":"VarChar(64)",
				"color_picker_favorite3":"VarChar(64)",
				"color_picker_favorite4":"VarChar(64)",
				"color_picker_favorite5":"VarChar(64)",
				"color_picker_favorite6":"VarChar(64)",
				"email_body_padding":"VarChar(64)",
				"email_body_width":"VarChar(64)",
				"heading_one_font":{
					"bold":"VarChar(64)",
					"color":"VarChar(64)",
					"font":"VarChar(64)",
					"font_style":"JSON",
					"italic":"VarChar(64)",
					"size":"Integer",
					"underline":"VarChar(64)"
				},
				"heading_two_font":{
					"bold":"VarChar(64)",
					"color":"VarChar(64)",
					"font":"VarChar(64)",
					"font_style":"JSON",
					"italic":"VarChar(64)",
					"size":"Integer",
					"underline":"VarChar(64)"
				},
				"links_font":{
					"bold":"VarChar(64)",
					"color":"VarChar(64)",
					"font":"VarChar(64)",
					"font_style":"JSON",
					"italic":"VarChar(64)",
					"size":"VarChar(64)",
					"underline":"VarChar(64)"
				},
				"primary_accent_color":"VarChar(64)",
				"primary_font":"VarChar(64)",
				"primary_font_color":"VarChar(64)",
				"primary_font_line_height":"VarChar(64)",
				"primary_font_size":"Integer",
				"secondary_accent_color":"VarChar(64)",
				"secondary_font":"VarChar(64)",
				"secondary_font_color":"VarChar(64)",
				"secondary_font_line_height":"VarChar(64)",
				"secondary_font_size":"Integer",
				"user_module_defaults":{
					"button_email":{
						"background_color":"VarChar(64)",
						"corner_radius":"Integer",
						"font":"VarChar(64)",
						"font_color":"VarChar(64)",
						"font_size":"Integer",
						"font_style":{
							"color":"VarChar(64)",
							"font":"VarChar(64)",
							"size":{
								"units":"VarChar(64)",
								"value":"Integer"
							},
							"styles":{
								"bold":"Boolean",
								"italic":"Boolean",
								"underline":"Boolean"
							}
						}
					},
					"email_divider":{
						"color":{
							"color":"VarChar(64)",
							"opacity":"Integer"
						},
						"height":"Integer",
						"line_type":"VarChar(64)"
					}
				}
			},
			"subcategory":"VarChar(64)",
			"subject":"VarChar(64)",
			"subscription":"Integer",
			"teamPerms":"JSON",
			"templatePath":"VarChar(87)",
			"transactional":"Boolean",
			"unpublishedAt":"Integer",
			"updated":"BigInt",
			"url":"VarChar(120)",
			"useRssHeadlineAsSubject":"Boolean",
			"userPerms":"JSON",
			"vidsExcluded":"JSON",
			"vidsIncluded":"JSON",
			"widgets":{
				"builtin_module_0_0_0":{
					"body":{
						"alignment":"VarChar(64)",
						"hs_enable_module_padding":"Boolean",
						"img":{
							"alt":"VarChar(64)",
							"height":"Integer",
							"src":"VarChar(207)",
							"width":"Integer"
						},
						"module_id":"Integer"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"builtin_module_1_0_0":{
					"body":{
						"alignment":"VarChar(64)",
						"hs_enable_module_padding":"Boolean",
						"img":{
							"alt":"VarChar(64)",
							"height":"Integer",
							"src":"VarChar(199)",
							"width":"Integer"
						},
						"module_id":"Integer"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"builtin_module_2_0_0":{
					"body":{
						"html":"VarChar(373)",
						"i18nKey":"VarChar(64)",
						"module_id":"Integer"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"builtin_module_3_0_0":{
					"body":{
						"alignment":"VarChar(64)",
						"hs_enable_module_padding":"Boolean",
						"img":{
							"alt":"VarChar(64)",
							"height":"Integer",
							"src":"VarChar(202)",
							"width":"Integer"
						},
						"module_id":"Integer"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"builtin_module_3_0_1":{
					"body":{
						"html":"VarChar(367)",
						"i18nKey":"VarChar(64)",
						"module_id":"Integer"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"builtin_module_3_1_0":{
					"body":{
						"alignment":"VarChar(64)",
						"hs_enable_module_padding":"Boolean",
						"img":{
							"alt":"VarChar(64)",
							"height":"Integer",
							"src":"VarChar(202)",
							"width":"Integer"
						},
						"module_id":"Integer"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"builtin_module_3_1_1":{
					"body":{
						"html":"VarChar(367)",
						"i18nKey":"VarChar(64)",
						"module_id":"Integer"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"builtin_module_5_0_0":{
					"body":{
						"html":"VarChar(282)",
						"i18nKey":"VarChar(64)",
						"module_id":"Integer"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"builtin_module_6_0_0":{
					"body":{
						"align":"VarChar(64)",
						"font":{
							"color":"VarChar(64)",
							"font":"VarChar(64)",
							"size":{
								"units":"VarChar(64)",
								"value":"Integer"
							},
							"styles":"JSON"
						},
						"hs_enable_module_padding":"Boolean",
						"link_font":{
							"color":"VarChar(64)",
							"font":"VarChar(64)",
							"size":{
								"units":"VarChar(64)",
								"value":"Integer"
							},
							"styles":{
								"bold":"Boolean",
								"italic":"Boolean",
								"text-decoration":"VarChar(64)",
								"underline":"Boolean"
							}
						},
						"module_id":"Integer",
						"unsubscribe_link_type":"VarChar(64)"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"module_153970326731935":{
					"body":{
						"alignment":"VarChar(64)",
						"background_color":"VarChar(64)",
						"corner_radius":"Integer",
						"destination":"VarChar(64)",
						"font_style":{
							"color":"VarChar(64)",
							"font":"VarChar(64)",
							"size":{
								"units":"VarChar(64)",
								"value":"Integer"
							},
							"styles":{
								"bold":"Boolean",
								"italic":"Boolean",
								"underline":"Boolean"
							}
						},
						"make_full_width":"Boolean",
						"module_id":"Integer",
						"text":"VarChar(64)"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"module_153978175731681":{
					"body":{
						"alignment":"VarChar(64)",
						"color":{
							"color":"VarChar(64)",
							"opacity":"Integer"
						},
						"css":"JSON",
						"height":"Integer",
						"hs_enable_module_padding":"Boolean",
						"line_type":"VarChar(64)",
						"module_id":"Integer",
						"width":"Integer"
					},
					"id":"VarChar(64)",
					"module_id":"Integer",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				},
				"preview_text":{
					"body":{
						"value":"VarChar(64)"
					},
					"id":"VarChar(64)",
					"name":"VarChar(64)",
					"order":"Integer",
					"type":"VarChar(64)"
				}
			},
			"author":"VarChar(64)",
			"authorName":"VarChar(64)",
			"campaign":"GUID",
			"campaignName":"VarChar(64)",
			"campaignUtm":"VarChar(64)",
			"createdById":"Integer",
			"emailbodyPlaintext":"VarChar(64)",
			"language":"VarChar(64)",
			"publishImmediately":"Boolean",
			"publishedByEmail":"VarChar(64)",
			"publishedById":"Integer",
			"publishedByName":"VarChar(64)",
			"subscriptionName":"VarChar(64)",
			"updatedById":"Integer"
		},
		"offset":"Integer",
		"total":"Integer",
		"totalCount":"Integer"
	}
}