SELECT * FROM AUTOREST.COMPANIESDATA


SELECT * FROM AUTOREST.COMPANYINFO WHERE COMPANYID IN (
2338459658,
2338459659,
2338459660,
2338459661
) 

SELECT * FROM AUTOREST.COMPANYPROPERTIES

SELECT * FROM AUTOREST.CONTACTSDATA

SELECT * FROM AUTOREST.CONTACTSLISTSDATA

SELECT * FROM AUTOREST.DEALPIPELINES

SELECT * FROM AUTOREST.DEALPIPELINESSTAGES

SELECT * FROM AUTOREST.DEALSDATA

SELECT * FROM AUTOREST.EMAILSDATA

SELECT * FROM AUTOREST.TICKETSDATA

 

SELECT * FROM AUTOREST."_CONFIGURATION"