{
	"v3_businesses_search":{
		"#path":[
			"http://api.yelp.com/v3/businesses/search"
		],
		"#maximumPageSize":32,
		"#firstrow":0,
		"#pageSizeParameter":"limit",
		"#rowOffsetParameter":"offset",
		"businesses[]":{
			"id":"VarChar(64)",
			"alias":"VarChar(64)",
			"name":"VarChar(64)",
			"image_url":"VarChar(102)",
			"is_closed":"Boolean",
			"url":"VarChar(295)",
			"review_count":"Integer",
			"categories[]":{
				"alias":"VarChar(21)",
				"title":"VarChar(33)"
			},
			"rating":"Double",
			"coordinates":{
				"latitude":"Double",
				"longitude":"Double"
			},
			"transactions[]":"VarChar(64)",
			"price":"VarChar(64)",
			"location":{
				"address1":"VarChar(64)",
				"address2":"VarChar(64)",
				"address3":"VarChar(64)",
				"city":"VarChar(64)",
				"zip_code":"Integer",
				"country":"VarChar(64)",
				"state":"VarChar(64)",
				"display_address[]":"VarChar(40)"
			},
			"phone":"VarChar(64)",
			"display_phone":"VarChar(64)",
			"distance":"Double"
		},
		"total":"Integer,#key",
		"region":{
			"center":{
				"longitude":"Double",
				"latitude":"Double"
			}
		},
		"location":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"27617",
			"#eq":"location"
		}
	},
	"categories":{
		"#path":[
			"http://api.yelp.com/v3/categories /categories"
		],
		"alias":"VarChar(48)",
		"title":"VarChar(52),#key",
		"parent_aliases[]":"VarChar(34)",
		"country_whitelist[]":"VarChar(3)",
		"country_blacklist[]":"VarChar(3)"
	}
}