SELECT * FROM AUTOREST.CATEGORIES;
SELECT * FROM AUTOREST.BUSINESSDELIVERYSEARCH WHERE LOCATION = 'Los Angeles' 
SELECT * FROM AUTOREST.BUSINESSPHONESEARCH WHERE QUERY_PHONE='+12132657775'
SELECT * FROM AUTOREST.BUSINESSSEARCH WHERE BUSINESSSEARCHROOT_LOCATION = 'Fresno'
SELECT * FROM AUTOREST.BUSINESS WHERE BUSINESSID='RxBjn1XKhSTeTZ7bqMVysA'
SELECT * FROM AUTOREST.REVIEWS WHERE REVIEWSROOT_BUSINESSID='nh2N06eY7k2l5r6KtxUYVg'
SELECT * FROM AUTOREST.BUSINESSMATCH WHERE NAME='Dog House Grill' AND ADDRESS1='2789 E Shaw Ave' AND CITY='Fresno' AND STATE='CA' AND COUNTRY = 'US'
SELECT * FROM AUTOREST.EVENTLOOKUP WHERE ID='san-francisco-yelp-10-year-anniversary-celebration'


SELECT * FROM AUTOREST."_CONFIGURATION"