{
	"categories":{
		"#path":[
			"https://api.yelp.com/v3/categories /categories"
		],
		"alias":"VarChar(48),#key",
		"title":"VarChar(54)",
		"parent_aliases<categories_parent_alias>[]":"VarChar(34)",
		"country_whitelist<categories_country_whitelist>[]":"VarChar(3)",
		"country_blacklist<categories_country_blacklist>[]":"VarChar(3)"
	},
	"events":{
		"#path":[
			"https://api.yelp.com/v3/events"
		],
		"#maximumPageSize": 50,
		"#firstrow": 0,
		"#pageSizeParameter": "limit",
		"#rowOffsetParameter": "offset",
		"events[]":{
			"attending_count":"Integer",
			"category":"VarChar(64)",
			"cost":"VarChar(64)",
			"cost_max":"VarChar(64)",
			"description":"VarChar(237)",
			"event_site_url":"VarChar(340)",
			"id":"VarChar(105)",
			"image_url":"VarChar(102)",
			"interested_count":"Integer",
			"is_canceled":"Boolean",
			"is_free":"Boolean",
			"is_official":"Boolean",
			"latitude":"Double",
			"longitude":"Double",
			"name":"VarChar(94)",
			"tickets_url":"VarChar(64)",
			"time_end":"Timestamp(0)",
			"time_start":"Timestamp(0)",
			"location":{
				"address1":"VarChar(64)",
				"address2":"VarChar(64)",
				"address3":"VarChar(64)",
				"city":"VarChar(64)",
				"zip_code":"Integer",
				"country":"VarChar(64)",
				"state":"VarChar(64)",
				"display_address<events_display_address>[]":"VarChar(64)",
				"cross_streets":"VarChar(64)"
			},
			"business_id":"VarChar(64)"
		},
		"total":"Integer,#key",
		"location":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"raleigh",
			"#eq":"location"
		}
	},
	"businesssearch<businesssearchroot>":{
		"#path":[
			"https://api.yelp.com/v3/businesses/search"
		],
		"#maximumPageSize": 50,
		"#firstrow": 0,
		"#pageSizeParameter": "limit",
		"#rowOffsetParameter": "offset",
		"businesses<businesssearch>[]":{
			"id":"VarChar(64)",
			"alias":"VarChar(64)",
			"name":"VarChar(64)",
			"image_url":"VarChar(102)",
			"is_closed":"Boolean",
			"url":"VarChar(298)",
			"review_count":"Integer",
			"categories<businesssearch_category>[]":{
				"alias":"VarChar(19)",
				"title":"VarChar(33)"
			},
			"rating":"Double",
			"coordinates":{
				"latitude":"Double",
				"longitude":"Double"
			},
			"transactions<businesssearch_transactions>[]":"VarChar(64)",
			"price":"VarChar(64)",
			"location":{
				"address1":"VarChar(64)",
				"address2":"VarChar(64)",
				"address3":"VarChar(64)",
				"city":"VarChar(64)",
				"zip_code":"Integer",
				"country":"VarChar(64)",
				"state":"VarChar(64)",
				"display_address<businesssearch_display_address>[]":"VarChar(40)"
			},
			"phone":"VarChar(64)",
			"display_phone":"VarChar(64)",
			"distance":"Double"
		},
		"total":"Integer,#key",
		"region":{
			"center":{
				"longitude":"Double",
				"latitude":"Double"
			}
		},
		"location":{
			"#type":"VarChar(100),#key",
			"#virtual":true,
			"#default":"27617",
			"#eq":"location"
		}
	},
	"businessphonesearch<businessphonesearch>":{
		"#path":[
			"https://api.yelp.com/v3/businesses/search/phone"
		],
		"businesses<businessphonesearch>[]":{
			"id":"VarChar(64)",
			"alias":"VarChar(64)",
			"name":"VarChar(64)",
			"image_url":"VarChar(102)",
			"is_closed":"Boolean",
			"url":"VarChar(258)",
			"review_count":"Integer",
			"categories<businessphonesearch_categories>[]":{
				"alias":"VarChar(64)",
				"title":"VarChar(64)"
			},
			"rating":"Double",
			"coordinates":{
				"latitude":"Double",
				"longitude":"Double"
			},
			"transactions":"JSON",
			"location":{
				"address1":"VarChar(64)",
				"address2":"VarChar(64)",
				"address3":"VarChar(64)",
				"city":"VarChar(64)",
				"zip_code":"Integer",
				"country":"VarChar(64)",
				"state":"VarChar(64)",
				"display_address<businessphonesearch_display_address>[]":"VarChar(64)"
			},
			"phone":"VarChar(64)",
			"display_phone":"VarChar(64)"
		},
		"total":"VarChar(100),#key",
		"phone<query_phone>":{
			"#type":"varchar(64),#key",
			"#virtual":true,
			"#default":"14159083801",
			"#eq":"phone"
		}
	},
	"deliverysearch<businessdeliverysearch>":{
		"#path":[
			"https://api.yelp.com/v3/transactions/delivery/search"
		],
		"#maximumPageSize": 50,
		"#firstrow": 0,
		"#pageSizeParameter": "limit",
		"#rowOffsetParameter": "offset",
		"businesses<businessdeliverysearch>[]":{
			"id":"VarChar(64)",
			"alias":"VarChar(64)",
			"name":"VarChar(64)",
			"image_url":"VarChar(102)",
			"is_closed":"Boolean",
			"url":"VarChar(312)",
			"review_count":"Integer",
			"categories<businessdeliverysearch_categories>[]":{
				"alias":"VarChar(64)",
				"title":"VarChar(64)"
			},
			"rating":"Double",
			"coordinates":{
				"latitude":"Double",
				"longitude":"Double"
			},
			"transactions<businessdeliverysearch_transactions>[]":"VarChar(64)",
			"price":"VarChar(64)",
			"location":{
				"address1":"VarChar(64)",
				"address2":"VarChar(64)",
				"address3":"VarChar(64)",
				"city":"VarChar(64)",
				"zip_code":"Integer",
				"country":"VarChar(64)",
				"state":"VarChar(64)",
				"display_address<businessdeliverysearch_display_address>[]":"VarChar(64)"
			},
			"phone":"VarChar(64)",
			"display_phone":"VarChar(64)"
		},
		"total":"Integer,#key",
		"location":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"raleigh",
			"#eq":"location"
		}
	},
	"business":{
		"#path":[
			"https://api.yelp.com/v3/businesses/{businessid}"
		],
		"id":"VarChar(64),#key",
		"alias":"VarChar(64)",
		"name":"VarChar(64)",
		"image_url":"VarChar(102)",
		"is_claimed":"Boolean",
		"is_closed":"Boolean",
		"url":"VarChar(271)",
		"phone":"VarChar(64)",
		"display_phone":"VarChar(64)",
		"review_count":"Integer",
		"categories<business_category>[]":{
			"alias":"VarChar(64)",
			"title":"VarChar(64)"
		},
		"rating":"Double",
		"location":{
			"address1":"VarChar(64)",
			"address2":"VarChar(64)",
			"address3":"VarChar(64)",
			"city":"VarChar(64)",
			"zip_code":"Integer",
			"country":"VarChar(64)",
			"state":"VarChar(64)",
			"display_address<business_display_address>[]":"VarChar(64)",
			"cross_streets":"VarChar(64)"
		},
		"coordinates":{
			"latitude":"Double",
			"longitude":"Double"
		},
		"photos<business_photos>[]":"VarChar(102)",
		"price":"VarChar(64)",
		"hours<business_hours>[]":{
			"open<business_open>[]":{
				"is_overnight":"Boolean",
				"start":"Integer",
				"end":"Integer",
				"day":"Integer"
			},
			"hours_type":"VarChar(64)",
			"is_open_now":"Boolean"
		},
		"transactions":"JSON",
		"businessid":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"WavvLdfdP6g8aZTtbBQHTw",
			"#eq":"businessid"
		}
	},
	"reviews<reviewsroot>":{
		"#path":[
			"https://api.yelp.com/v3/businesses/{businessid}/reviews"
		],
		"reviews<reviews>[]":{
			"id":"VarChar(64)",
			"url":"VarChar(315)",
			"text":"VarChar(237)",
			"rating":"Integer",
			"time_created":"Timestamp(0)",
			"user":{
				"id":"VarChar(64)",
				"profile_url":"VarChar(94)",
				"image_url":"VarChar(100)",
				"name":"VarChar(64)"
			}
		},
		"total":"Integer,#key",
		"possible_languages<reviews_possible_languages>[]":"VarChar(64)",
		"businessid":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"WavvLdfdP6g8aZTtbBQHTw",
			"#eq":"businessid"
		}
	},
	"businessmatch":{
		"#path":[
			"https://api.yelp.com/v3/businesses/matches /businesses"
		],
		"id":"VarChar(64),#key",
		"alias":"VarChar(64)",
		"name":{
			"#type":"VarChar(64)",
			"#default":"Gary Danko",
			"#eq":"name"
		},
		"coordinates":{
			"latitude":"Double",
			"longitude":"Double"
		},
		"location":{
			"address1":"VarChar(64)",
			"address2":"VarChar(64)",
			"address3":"VarChar(64)",
			"city":"VarChar(64)",
			"zip_code":"Integer",
			"country":"VarChar(64)",
			"state":"VarChar(64)",
			"display_address<businessmatch_display_address>[]":"VarChar(64)"
		},
		"phone":"VarChar(64)",
		"display_phone":"VarChar(64)",
		"address1":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"800 N Point St",
			"#eq":"address1"
		},
		"city":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"San francisco",
			"#eq":"city"
		},
		"state":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"ca",
			"#eq":"state"
		},
		"country":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"US",
			"#eq":"country"
		}
	},
	"eventlookup":{
		"#path":[
			"https://api.yelp.com/v3/events/{id}"
		],
		"attending_count":"Integer,#key",
		"category":"VarChar(64)",
		"cost":"VarChar(64)",
		"cost_max":"VarChar(64)",
		"description":"VarChar(238)",
		"event_site_url":"VarChar(310)",
		"id":{
			"#type":"VarChar(75)",
			"#default":"san-francisco-yelp-10-year-anniversary-celebration",
			"#eq":"id"
		},
		"image_url":"VarChar(102)",
		"interested_count":"Integer",
		"is_canceled":"Boolean",
		"is_free":"Boolean",
		"is_official":"Boolean",
		"latitude":"Double",
		"longitude":"Double",
		"name":"VarChar(64)",
		"tickets_url":"VarChar(64)",
		"time_end":"Timestamp(0)",
		"time_start":"Timestamp(0)",
		"location":{
			"address1":"VarChar(64)",
			"address2":"VarChar(64)",
			"address3":"VarChar(64)",
			"city":"VarChar(64)",
			"zip_code":"VarChar(64)",
			"country":"VarChar(64)",
			"state":"VarChar(64)",
			"display_address<eventlookup_display_address>[]":"VarChar(64)",
			"cross_streets":"VarChar(64)"
		},
		"business_id":"VarChar(64)"
	}
}