SELECT * FROM AUTOREST."_CONFIGURATION"


SELECT * FROM AUTOREST.ATTACHMENT
SELECT * FROM AUTOREST.TABLE_ASTCONTRACT
SELECT * FROM AUTOREST.CATALOGS
SELECT * FROM AUTOREST.TABLE_QUESTION
SELECT * FROM AUTOREST.PA_SCORECARDS
SELECT * FROM AUTOREST.TABLE_SLA
SELECT * FROM AUTOREST.SC_SERVICECATALOG_CATALOGS
SELECT * FROM AUTOREST.SC_SERVICECATALOG_ITEMS