{
"TABLE_ASTContract":"https://dev66303.service-now.com/api/now/table/ast_contract",
"TABLE_ASTLICENSE":"https://dev66303.service-now.com/api/now/table/ast_license_base",
"TABLE_ChangeRequest":"https://dev66303.service-now.com/api/now/table/change_request",
"TABLE_CmdbCi":"https://dev66303.service-now.com/api/now/table/cmdb_ci",
"TABLE_Cmdb_CI_app_server":"https://dev66303.service-now.com/api/now/table/cmdb_ci_app_server",
"TABLE_Cmdb_CI_ci_appl":"https://dev66303.service-now.com/api/now/table/cmdb_ci_appl",
"TABLE_Cmdb_CI_ci_cluster":"https://dev66303.service-now.com/api/now/table/cmdb_ci_cluster",
"TABLE_Cmdb_CI_cluster_node":"https://dev66303.service-now.com/api/now/table/cmdb_ci_cluster_node",
"TABLE_Cmdb_CI_cluster_resource":"https://dev66303.service-now.com/api/now/table/cmdb_ci_cluster_resource",
"TABLE_Cmdb_CI_ci_computer":"https://dev66303.service-now.com/api/now/table/cmdb_ci_computer",
"TABLE_Cmdb_CI_db_catalog":"https://dev66303.service-now.com/api/now/table/cmdb_ci_db_catalog",
"TABLE_Cmdb_CI_db_instance":"https://dev66303.service-now.com/api/now/table/cmdb_ci_db_instance",
"TABLE_Cmdb_CI_file_system":"https://dev66303.service-now.com/api/now/table/cmdb_ci_file_system",
"TABLE_Cmdb_CI_infra_service":"https://dev66303.service-now.com/api/now/table/cmdb_ci_infra_service",
"TABLE_Cmdb_CI_ip_service":"https://dev66303.service-now.com/api/now/table/cmdb_ci_ip_service",
"TABLE_Cmdb_CI_ci_netgear":"https://dev66303.service-now.com/api/now/table/cmdb_ci_netgear",
"TABLE_Cmdb_CI_ci_server":"https://dev66303.service-now.com/api/now/table/cmdb_ci_server",
"TABLE_Cmdb_CI_ci_spkg":"https://dev66303.service-now.com/api/now/table/cmdb_ci_spkg",
"TABLE_Cmdb_CI_unix_server":"https://dev66303.service-now.com/api/now/table/cmdb_ci_unix_server",
"TABLE_Cmdb_CI_ci_vm":"https://dev66303.service-now.com/api/now/table/cmdb_ci_vm",
"TABLE_Cmdb_CI_web_server":"https://dev66303.service-now.com/api/now/table/cmdb_ci_web_server",
"TABLE_CmdbMetric":"https://dev66303.service-now.com/api/now/table/cmdb_metric",
"TABLE_DiagrammerAction":"https://dev66303.service-now.com/api/now/table/diagrammer_action",
"TABLE_DiscoveryProbes":"https://dev66303.service-now.com/api/now/table/discovery_probes",
"TABLE_Ecc_AGENT_agent_metric":"https://dev66303.service-now.com/api/now/table/ecc_agent_metric",
"TABLE_ExpertPanel":"https://dev66303.service-now.com/api/now/table/expert_panel",
"TABLE_ProcessStep":"https://dev66303.service-now.com/api/now/table/process_step",
"TABLE_Item_OPTION_option_new":"https://dev66303.service-now.com/api/now/table/item_option_new",
"TABLE_Question":"https://dev66303.service-now.com/api/now/table/question",
"TABLE_Sc_CAT_cat_item":"https://dev66303.service-now.com/api/now/table/sc_cat_item",
"TABLE_Sc_CAT_ITEM_delivery_task":"https://dev66303.service-now.com/api/now/table/sc_cat_item_delivery_task",
"TABLE_ScCategory":"https://dev66303.service-now.com/api/now/table/sc_category",
"TABLE_Scheduled_DATA_data_import":"https://dev66303.service-now.com/api/now/table/scheduled_data_import",
"TABLE_Sla":"https://dev66303.service-now.com/api/now/table/sla",
"TABLE_SysDictionary":"https://dev66303.service-now.com/api/now/table/sys_dictionary",
"TABLE_Sys_IMPORT_set_row":"https://dev66303.service-now.com/api/now/table/sys_import_set_row",
"TABLE_Sys_script_client":"https://dev66303.service-now.com/api/now/table/sys_script_client",
"TABLE_Sys_UI_policy":"https://dev66303.service-now.com/api/now/table/sys_ui_policy",
"TABLE_Sys_UI_policy_action":"https://dev66303.service-now.com/api/now/table/sys_ui_policy_action",
"TABLE_Sysauto":"https://dev66303.service-now.com/api/now/table/sysauto",
"TABLE_SysautoScript":"https://dev66303.service-now.com/api/now/table/sysauto_script",
"TABLE_Syslog":"https://dev66303.service-now.com/api/now/table/syslog",
"TABLE_Sysrule":"https://dev66303.service-now.com/api/now/table/sysrule",
"TABLE_SysruleEscalate":"https://dev66303.service-now.com/api/now/table/sysrule_escalate",
"TABLE_Task":"https://dev66303.service-now.com/api/now/table/task",
"TABLE_V_FIELD_field_creator":"https://dev66303.service-now.com/api/now/table/v_field_creator",
"TABLE_V_FIELD_field_editor":"https://dev66303.service-now.com/api/now/table/v_field_editor",
"TABLE_V_TABLE_table_creator":"https://dev66303.service-now.com/api/now/table/v_table_creator",
"TABLE_V_WS_ws_creator":"https://dev66303.service-now.com/api/now/table/v_ws_creator",
"TABLE_VarDictionary":"https://dev66303.service-now.com/api/now/table/var_dictionary",
"SC_ServiceCatalog_Catalogs":"https://dev66303.service-now.com/api/sn_sc/v1/servicecatalog/catalogs",
"SC_ServiceCatalog_Items":"https://dev66303.service-now.com/api/sn_sc/v1/servicecatalog/items",
"SC_ServiceCatalog_Cart":"https://dev66303.service-now.com/api/sn_sc/v1/servicecatalog/cart",
"PA_ScoreCards": "https://dev66303.service-now.com/api/now/pa/scorecards",
"Attachment": "https://dev66303.service-now.com/api/now/attachment"
}



