{
	"TABLE_ASTContract":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/ast_contract /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"cost_adjustment_percentage":"Integer,#key",
		"total_cost":"Integer",
		"discount":"Double",
		"cost_adjustment":"Integer",
		"renewal_end_date":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"tax_rate":"Double",
		"approval_history":"VarChar(64)",
		"number":"VarChar(16)",
		"tax_cost":"Integer",
		"sys_updated_by":"VarChar(9)",
		"renewal_date":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sub_total_cost":"Integer",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(9)"
		},
		"cost_adjustment_reason":"VarChar(64)",
		"parent_contract":"VarChar(64)",
		"state":"VarChar(13)",
		"starts":"Date",
		"sys_created_by":"VarChar(7)",
		"tax_exempt":"VarChar(7)",
		"yearly_cost":"Integer",
		"active":"VarChar(6)",
		"commitment":"Integer",
		"payment_amount":"Integer",
		"sys_domain_path":"VarChar(1)",
		"payment_schedule":"VarChar(10)",
		"terms_and_conditions":"LongVarChar(19974)",
		"cost_center":"VarChar(64)",
		"renewable":"VarChar(7)",
		"renewal_contact":"VarChar(64)",
		"expiration":{
			"link":"VarChar(151)",
			"value":"VarChar(64)"
		},
		"invoice_payment_terms":"VarChar(64)",
		"contract_administrator":{
			"link":"VarChar(132)",
			"value":"VarChar(64)"
		},
		"short_description":"VarChar(79)",
		"ratecard":"VarChar(7)",
		"cost_adjustment_type":"VarChar(64)",
		"description":"VarChar(130)",
		"sys_class_name":"VarChar(18)",
		"sys_id":"VarChar(48)",
		"po_number":"VarChar(64)",
		"license_quantity_entitled":"VarChar(64)",
		"vendor":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"ends":"Date",
		"contract_model":{
			"link":"VarChar(135)",
			"value":"VarChar(48)"
		},
		"approver":{
			"link":"VarChar(132)",
			"value":"VarChar(64)"
		},
		"process":"VarChar(64)",
		"monthly_cost":"Double",
		"vendor_contract":"VarChar(64)",
		"license_type":"VarChar(64)",
		"lifetime_cost":"Integer",
		"renewal_options":"VarChar(64)",
		"sys_mod_count":"Integer",
		"sys_tags":"VarChar(64)",
		"sales_tax":"VarChar(7)",
		"substate":"VarChar(64)",
		"application_model":"VarChar(64)",
		"cost_per_unit":"Double",
		"location":"VarChar(64)",
		"vendor_account":"VarChar(64)"
	},
	"TABLE_ASTLICENSE":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/ast_license_base /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"parent":"VarChar(64)",
		"short_description":"VarChar(82)",
		"total_cost":"Integer,#key",
		"discoverable_key":"VarChar(64)",
		"description":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"install_count":"Integer",
		"manual":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"number":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"po_number":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"vendor":"VarChar(64)",
		"upgraded_from":"VarChar(64)",
		"department":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"license_cost":"Integer",
		"sys_created_by":"VarChar(64)",
		"license_available":"Integer",
		"vendor_contract":"VarChar(64)",
		"license_count":"Integer",
		"sys_mod_count":"Integer",
		"sys_tags":"VarChar(64)",
		"license_key":"VarChar(64)",
		"percent_used":"Integer",
		"purchased":"Date",
		"location":"VarChar(64)",
		"vendor_account":"VarChar(64)",
		"maintenance_cost":"Integer",
		"option":"VarChar(64)"
	},
	"TABLE_ChangeRequest":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/change_request /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"parent":"VarChar(64)",
		"reason":"VarChar(64)",
		"made_sla":"VarChar(7),#key",
		"backout_plan":"VarChar(529)",
		"watch_list":"VarChar(64)",
		"upon_reject":"VarChar(9)",
		"sys_updated_on":"Timestamp(0)",
		"type":"VarChar(13)",
		"conflict_status":"VarChar(16)",
		"approval_history":"VarChar(64)",
		"number":"VarChar(15)",
		"test_plan":"VarChar(441)",
		"cab_delegate":"VarChar(64)",
		"sys_updated_by":"VarChar(13)",
		"opened_by":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"user_input":"VarChar(64)",
		"requested_by_date":"Timestamp(0)",
		"sys_created_on":"Timestamp(0)",
		"on_hold_task":"VarChar(64)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(9)"
		},
		"state":"Integer",
		"sys_created_by":"VarChar(19)",
		"knowledge":"VarChar(7)",
		"order":"VarChar(64)",
		"phase":"VarChar(13)",
		"closed_at":"Timestamp(0)",
		"cmdb_ci":{
			"link":"VarChar(130)",
			"value":"VarChar(48)"
		},
		"delivery_plan":"VarChar(64)",
		"impact":"Integer",
		"active":"VarChar(7)",
		"review_comments":"VarChar(64)",
		"work_notes_list":"VarChar(64)",
		"business_service":"VarChar(64)",
		"priority":"Integer",
		"sys_domain_path":"VarChar(1)",
		"time_worked":"VarChar(64)",
		"cab_recommendation":"VarChar(64)",
		"expected_start":"VarChar(64)",
		"production_system":"VarChar(7)",
		"opened_at":"Timestamp(0)",
		"review_date":"VarChar(64)",
		"business_duration":"VarChar(64)",
		"group_list":"VarChar(64)",
		"requested_by":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"work_end":"Timestamp(0)",
		"change_plan":"VarChar(576)",
		"phase_state":"VarChar(6)",
		"approval_set":"Timestamp(0)",
		"cab_date":"VarChar(64)",
		"work_notes":"VarChar(64)",
		"implementation_plan":"VarChar(2101)",
		"end_date":"Timestamp(0)",
		"short_description":"VarChar(136)",
		"close_code":"VarChar(64)",
		"correlation_display":"VarChar(64)",
		"delivery_task":"VarChar(64)",
		"work_start":"Timestamp(0)",
		"assignment_group":{
			"link":"VarChar(141)",
			"value":"VarChar(48)"
		},
		"additional_assignee_list":"VarChar(64)",
		"outside_maintenance_schedule":"VarChar(7)",
		"description":"VarChar(415)",
		"on_hold_reason":"VarChar(64)",
		"calendar_duration":"VarChar(64)",
		"std_change_producer_version":{
			"link":"VarChar(160)",
			"value":"VarChar(64)"
		},
		"close_notes":"VarChar(70)",
		"sys_class_name":"VarChar(21)",
		"closed_by":{
			"link":"VarChar(132)",
			"value":"VarChar(64)"
		},
		"follow_up":"VarChar(64)",
		"sys_id":"VarChar(48)",
		"contact_type":"VarChar(64)",
		"cab_required":"VarChar(7)",
		"urgency":"Integer",
		"scope":"Integer",
		"company":"VarChar(64)",
		"justification":"VarChar(99)",
		"reassignment_count":"Integer",
		"review_status":"VarChar(64)",
		"activity_due":"VarChar(64)",
		"assigned_to":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"start_date":"Timestamp(0)",
		"comments":"VarChar(64)",
		"approval":"VarChar(19)",
		"sla_due":"VarChar(64)",
		"comments_and_work_notes":"VarChar(64)",
		"due_date":"VarChar(64)",
		"sys_mod_count":"Integer",
		"on_hold":"VarChar(7)",
		"sys_tags":"VarChar(64)",
		"conflict_last_run":"Timestamp(0)",
		"escalation":"Integer",
		"upon_approval":"VarChar(10)",
		"correlation_id":"VarChar(64)",
		"location":"VarChar(64)",
		"risk":"Integer",
		"category":"VarChar(19)",
		"risk_impact_analysis":"VarChar(64)"
	},
	"TABLE_CmdbCi":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"skip_sync":"VarChar(7),#key",
		"operational_status":"Integer",
		"sys_updated_on":"Timestamp(0)",
		"discovery_source":"VarChar(22)",
		"first_discovered":"Timestamp(0)",
		"sys_updated_by":"VarChar(16)",
		"due_in":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(9)"
		},
		"install_date":"Timestamp(0)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(19)",
		"warranty_expiration":"Date",
		"asset_tag":"VarChar(12)",
		"fqdn":"VarChar(64)",
		"change_control":{
			"link":"VarChar(141)",
			"value":"VarChar(64)"
		},
		"owned_by":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"checked_out":"VarChar(64)",
		"sys_domain_path":"VarChar(1)",
		"delivery_date":"Timestamp(0)",
		"maintenance_schedule":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"install_status":"Integer",
		"cost_center":{
			"link":"VarChar(142)",
			"value":"VarChar(48)"
		},
		"supported_by":{
			"link":"VarChar(132)",
			"value":"VarChar(64)"
		},
		"dns_domain":"VarChar(64)",
		"name":"VarChar(103)",
		"assigned":"Timestamp(0)",
		"purchase_date":"Date",
		"subcategory":"VarChar(12)",
		"short_description":"VarChar(105)",
		"assignment_group":"VarChar(64)",
		"managed_by":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"can_print":"VarChar(7)",
		"last_discovered":"Timestamp(0)",
		"sys_class_name":"VarChar(36)",
		"manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"sys_id":"VarChar(48)",
		"po_number":"VarChar(12)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(27)",
		"mac_address":"VarChar(64)",
		"vendor":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"company":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":{
			"link":"VarChar(141)",
			"value":"VarChar(48)"
		},
		"assigned_to":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"start_date":"VarChar(64)",
		"comments":"VarChar(121)",
		"cost":"Double",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(7)",
		"serial_number":"VarChar(25)",
		"ip_address":"VarChar(64)",
		"model_id":{
			"link":"VarChar(135)",
			"value":"VarChar(48)"
		},
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(4)",
		"order_date":"Timestamp(0)",
		"schedule":"VarChar(64)",
		"support_group":{
			"link":"VarChar(141)",
			"value":"VarChar(48)"
		},
		"due":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(7)",
		"attributes":"VarChar(64)",
		"location":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"asset":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"category":"VarChar(34)",
		"fault_count":"Integer",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_app_server":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_app_server /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"container":"VarChar(64)",
		"tcp_port":"VarChar(64)",
		"skip_sync":"VarChar(64),#key",
		"operational_status":"Integer",
		"running_process_command":"VarChar(64)",
		"pid":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"running_process_key_parameters":"VarChar(64)",
		"rp_command_hash":"VarChar(64)",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"due_in":"VarChar(64)",
		"install_directory":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(64)"
		},
		"used_for":"VarChar(64)",
		"install_date":"VarChar(64)",
		"is_clustered":"VarChar(64)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(64)",
		"warranty_expiration":"VarChar(64)",
		"asset_tag":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"rp_key_parameters_hash":"VarChar(64)",
		"sys_domain_path":"VarChar(64)",
		"version":"VarChar(64)",
		"delivery_date":"VarChar(64)",
		"maintenance_schedule":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"install_status":"Integer",
		"cost_center":"VarChar(64)",
		"supported_by":"VarChar(64)",
		"dns_domain":"VarChar(64)",
		"name":"VarChar(64)",
		"assigned":"VarChar(64)",
		"purchase_date":"VarChar(64)",
		"subcategory":"VarChar(64)",
		"short_description":"VarChar(64)",
		"assignment_group":"VarChar(64)",
		"managed_by":"VarChar(64)",
		"edition":"VarChar(64)",
		"can_print":"VarChar(64)",
		"last_discovered":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"manufacturer":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(64)",
		"mac_address":"VarChar(64)",
		"vendor":"VarChar(64)",
		"company":"VarChar(64)",
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":"VarChar(64)",
		"config_file":"VarChar(64)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"VarChar(64)",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(64)",
		"serial_number":"VarChar(64)",
		"ip_address":"VarChar(64)",
		"model_id":"VarChar(64)",
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(64)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"support_group":"VarChar(64)",
		"due":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(64)",
		"attributes":"VarChar(64)",
		"location":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"asset":"VarChar(64)",
		"category":"VarChar(64)",
		"fault_count":"Integer",
		"config_directory":"VarChar(64)",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_ci_appl":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_appl /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"tcp_port":"VarChar(64)",
		"skip_sync":"VarChar(64),#key",
		"operational_status":"Integer",
		"running_process_command":"VarChar(64)",
		"pid":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"running_process_key_parameters":"VarChar(64)",
		"rp_command_hash":"VarChar(64)",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"due_in":"VarChar(64)",
		"install_directory":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(64)"
		},
		"used_for":"VarChar(64)",
		"install_date":"Timestamp(0)",
		"is_clustered":"VarChar(64)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(64)",
		"warranty_expiration":"VarChar(64)",
		"asset_tag":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"rp_key_parameters_hash":"VarChar(64)",
		"sys_domain_path":"VarChar(64)",
		"version":"Double",
		"delivery_date":"VarChar(64)",
		"maintenance_schedule":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"install_status":"Integer",
		"cost_center":"VarChar(64)",
		"supported_by":"VarChar(64)",
		"dns_domain":"VarChar(64)",
		"name":"VarChar(64)",
		"assigned":"VarChar(64)",
		"purchase_date":"VarChar(64)",
		"subcategory":"VarChar(64)",
		"short_description":"VarChar(64)",
		"assignment_group":"VarChar(64)",
		"managed_by":"VarChar(64)",
		"edition":"VarChar(64)",
		"can_print":"VarChar(64)",
		"last_discovered":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"sys_id":"VarChar(64)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(64)",
		"mac_address":"VarChar(64)",
		"vendor":"VarChar(64)",
		"company":"VarChar(64)",
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":"VarChar(64)",
		"config_file":"VarChar(64)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"VarChar(64)",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(64)",
		"serial_number":"VarChar(64)",
		"ip_address":"VarChar(64)",
		"model_id":"VarChar(64)",
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(64)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"support_group":{
			"link":"VarChar(141)",
			"value":"VarChar(64)"
		},
		"due":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(64)",
		"attributes":"VarChar(64)",
		"location":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"asset":{
			"link":"VarChar(133)",
			"value":"VarChar(64)"
		},
		"category":"VarChar(64)",
		"fault_count":"Integer",
		"config_directory":"VarChar(64)",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_ci_cluster":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_cluster /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"skip_sync":"VarChar(64),#key",
		"operational_status":"Integer",
		"cluster_type":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"cluster_status":"VarChar(64)",
		"due_in":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(64)"
		},
		"install_date":"VarChar(64)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(64)",
		"warranty_expiration":"VarChar(64)",
		"cluster_version":"VarChar(64)",
		"asset_tag":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"sys_domain_path":"VarChar(64)",
		"delivery_date":"VarChar(64)",
		"maintenance_schedule":"VarChar(64)",
		"install_status":"Integer",
		"cost_center":"VarChar(64)",
		"supported_by":"VarChar(64)",
		"dns_domain":"VarChar(64)",
		"name":"VarChar(64)",
		"assigned":"VarChar(64)",
		"purchase_date":"VarChar(64)",
		"subcategory":"VarChar(64)",
		"short_description":"VarChar(64)",
		"assignment_group":"VarChar(64)",
		"managed_by":"VarChar(64)",
		"can_print":"VarChar(64)",
		"last_discovered":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"manufacturer":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"cluster_id":"VarChar(64)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(64)",
		"mac_address":"VarChar(64)",
		"vendor":"VarChar(64)",
		"company":"VarChar(64)",
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":"VarChar(64)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"VarChar(64)",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(64)",
		"serial_number":"VarChar(64)",
		"ip_address":"VarChar(64)",
		"model_id":"VarChar(64)",
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(64)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"support_group":"VarChar(64)",
		"due":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(64)",
		"attributes":"VarChar(64)",
		"location":"VarChar(64)",
		"asset":"VarChar(64)",
		"category":"VarChar(64)",
		"fault_count":"Integer",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_cluster_node":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_cluster_node /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"cluster":{
			"link":"VarChar(142)",
			"value":"VarChar(64),#key"
		},
		"skip_sync":"VarChar(64)",
		"operational_status":"Integer",
		"sys_updated_on":"Timestamp(0)",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"due_in":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(64)"
		},
		"install_date":"VarChar(64)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(64)",
		"warranty_expiration":"VarChar(64)",
		"asset_tag":"VarChar(64)",
		"node_status":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"sys_domain_path":"VarChar(64)",
		"delivery_date":"VarChar(64)",
		"maintenance_schedule":"VarChar(64)",
		"install_status":"Integer",
		"cost_center":"VarChar(64)",
		"supported_by":"VarChar(64)",
		"dns_domain":"VarChar(64)",
		"name":"VarChar(64)",
		"assigned":"VarChar(64)",
		"purchase_date":"VarChar(64)",
		"subcategory":"VarChar(64)",
		"server":{
			"link":"VarChar(141)",
			"value":"VarChar(64)"
		},
		"short_description":"VarChar(64)",
		"assignment_group":"VarChar(64)",
		"managed_by":"VarChar(64)",
		"can_print":"VarChar(64)",
		"last_discovered":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"manufacturer":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(64)",
		"mac_address":"VarChar(64)",
		"vendor":"VarChar(64)",
		"company":"VarChar(64)",
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":"VarChar(64)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"VarChar(64)",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(64)",
		"serial_number":"VarChar(64)",
		"ip_address":"VarChar(64)",
		"model_id":{
			"link":"VarChar(135)",
			"value":"VarChar(64)"
		},
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(64)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"support_group":"VarChar(64)",
		"due":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(64)",
		"attributes":"VarChar(64)",
		"location":"VarChar(64)",
		"asset":"VarChar(64)",
		"category":"VarChar(64)",
		"fault_count":"Integer",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_cluster_resource":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_cluster_resource /result"
		]
	},
	"TABLE_Cmdb_CI_ci_computer":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_computer /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"os_address_width":"VarChar(64)",
		"skip_sync":"VarChar(7),#key",
		"operational_status":"Integer",
		"os_service_pack":"VarChar(21)",
		"cpu_core_thread":"VarChar(64)",
		"cpu_manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"sys_updated_on":"Timestamp(0)",
		"discovery_source":"VarChar(22)",
		"first_discovered":"Timestamp(0)",
		"sys_updated_by":"VarChar(16)",
		"due_in":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"cpu_type":"VarChar(48)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(9)"
		},
		"install_date":"Timestamp(0)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(19)",
		"ram":"Integer",
		"warranty_expiration":"Date",
		"asset_tag":"VarChar(12)",
		"cpu_name":"VarChar(70)",
		"hardware_substatus":"VarChar(13)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"cpu_speed":"Integer",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"disk_space":"Double",
		"sys_domain_path":"VarChar(1)",
		"object_id":"VarChar(64)",
		"delivery_date":"Timestamp(0)",
		"maintenance_schedule":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"hardware_status":"VarChar(13)",
		"install_status":"Integer",
		"cost_center":{
			"link":"VarChar(142)",
			"value":"VarChar(48)"
		},
		"supported_by":"VarChar(64)",
		"dns_domain":"VarChar(64)",
		"name":"VarChar(64)",
		"assigned":"Timestamp(0)",
		"purchase_date":"Date",
		"subcategory":"VarChar(12)",
		"cd_speed":"Integer",
		"default_gateway":"VarChar(64)",
		"short_description":"VarChar(105)",
		"chassis_type":"VarChar(64)",
		"virtual":"VarChar(7)",
		"assignment_group":"VarChar(64)",
		"floppy":"VarChar(64)",
		"managed_by":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"os_domain":"VarChar(64)",
		"can_print":"VarChar(7)",
		"last_discovered":"Timestamp(0)",
		"sys_class_name":"VarChar(33)",
		"cpu_count":"Integer",
		"manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"sys_id":"VarChar(48)",
		"po_number":"VarChar(12)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(27)",
		"mac_address":"VarChar(64)",
		"vendor":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"company":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":{
			"link":"VarChar(141)",
			"value":"VarChar(48)"
		},
		"assigned_to":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"start_date":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"Double",
		"os":"VarChar(45)",
		"os_version":"VarChar(28)",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(7)",
		"serial_number":"VarChar(25)",
		"ip_address":"VarChar(64)",
		"model_id":{
			"link":"VarChar(135)",
			"value":"VarChar(48)"
		},
		"sys_tags":"VarChar(64)",
		"cd_rom":"VarChar(7)",
		"cost_cc":"VarChar(4)",
		"order_date":"Timestamp(0)",
		"schedule":"VarChar(64)",
		"support_group":"VarChar(64)",
		"due":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(7)",
		"attributes":"VarChar(64)",
		"location":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"asset":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"category":"VarChar(34)",
		"fault_count":"Integer",
		"cpu_core_count":"Integer",
		"form_factor":"VarChar(64)",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_db_catalog":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_db_catalog /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"skip_sync":"VarChar(64),#key",
		"operational_status":"Integer",
		"sys_updated_on":"Timestamp(0)",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"due_in":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(64)"
		},
		"install_date":"VarChar(64)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(64)",
		"warranty_expiration":"VarChar(64)",
		"asset_tag":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"sys_domain_path":"VarChar(64)",
		"delivery_date":"VarChar(64)",
		"maintenance_schedule":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"install_status":"Integer",
		"cost_center":"VarChar(64)",
		"supported_by":"VarChar(64)",
		"dns_domain":"VarChar(64)",
		"name":"VarChar(64)",
		"assigned":"VarChar(64)",
		"purchase_date":"VarChar(64)",
		"subcategory":"VarChar(64)",
		"short_description":"VarChar(64)",
		"assignment_group":"VarChar(64)",
		"managed_by":"VarChar(64)",
		"can_print":"VarChar(64)",
		"last_discovered":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"manufacturer":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(64)",
		"mac_address":"VarChar(64)",
		"vendor":"VarChar(64)",
		"company":"VarChar(64)",
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":"VarChar(64)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"VarChar(64)",
		"database_instance":"VarChar(64)",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(64)",
		"serial_number":"VarChar(64)",
		"ip_address":"VarChar(64)",
		"model_id":"VarChar(64)",
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(64)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"support_group":"VarChar(64)",
		"due":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(64)",
		"attributes":"VarChar(64)",
		"location":"VarChar(64)",
		"asset":"VarChar(64)",
		"category":"VarChar(64)",
		"fault_count":"Integer",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_db_instance":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_db_instance /result"
		]
	},
	"TABLE_Cmdb_CI_file_system":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_file_system /result"
		]
	},
	"TABLE_Cmdb_CI_infra_service":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_infra_service /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"tcp_port":"VarChar(64)",
		"skip_sync":"VarChar(64),#key",
		"operational_status":"Integer",
		"running_process_command":"VarChar(64)",
		"pid":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"running_process_key_parameters":"VarChar(64)",
		"rp_command_hash":"VarChar(64)",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"due_in":"VarChar(64)",
		"install_directory":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(64)"
		},
		"used_for":"VarChar(64)",
		"install_date":"Timestamp(0)",
		"is_clustered":"VarChar(64)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(64)",
		"warranty_expiration":"VarChar(64)",
		"asset_tag":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"rp_key_parameters_hash":"VarChar(64)",
		"sys_domain_path":"VarChar(64)",
		"version":"Double",
		"delivery_date":"VarChar(64)",
		"maintenance_schedule":"VarChar(64)",
		"install_status":"Integer",
		"cost_center":"VarChar(64)",
		"supported_by":"VarChar(64)",
		"dns_domain":"VarChar(64)",
		"name":"VarChar(64)",
		"provided_by":"VarChar(64)",
		"assigned":"VarChar(64)",
		"purchase_date":"VarChar(64)",
		"subcategory":"VarChar(64)",
		"short_description":"VarChar(64)",
		"assignment_group":"VarChar(64)",
		"managed_by":"VarChar(64)",
		"edition":"VarChar(64)",
		"can_print":"VarChar(64)",
		"last_discovered":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"sys_id":"VarChar(64)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(64)",
		"mac_address":"VarChar(64)",
		"vendor":"VarChar(64)",
		"company":"VarChar(64)",
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":"VarChar(64)",
		"config_file":"VarChar(64)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"VarChar(64)",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(64)",
		"serial_number":"VarChar(64)",
		"ip_address":"VarChar(64)",
		"model_id":"VarChar(64)",
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(64)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"support_group":{
			"link":"VarChar(141)",
			"value":"VarChar(64)"
		},
		"due":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(64)",
		"attributes":"VarChar(64)",
		"location":"VarChar(64)",
		"asset":{
			"link":"VarChar(133)",
			"value":"VarChar(64)"
		},
		"category":"VarChar(64)",
		"fault_count":"Integer",
		"config_directory":"VarChar(64)",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_ip_service":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_ip_service /result"
		]
	},
	"TABLE_Cmdb_CI_ci_netgear":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_netgear /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"can_switch":"VarChar(64),#key",
		"skip_sync":"VarChar(64)",
		"operational_status":"Integer",
		"cpu_manufacturer":"VarChar(64)",
		"device_type":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"due_in":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"can_partitionvlans":"VarChar(64)",
		"cpu_type":"VarChar(64)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(64)"
		},
		"install_date":"Timestamp(0)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(64)",
		"ram":"Integer",
		"warranty_expiration":"VarChar(64)",
		"asset_tag":"VarChar(64)",
		"hardware_substatus":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"cpu_speed":"VarChar(64)",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"firmware_manufacturer":"VarChar(64)",
		"disk_space":"VarChar(64)",
		"physical_interface_count":"VarChar(64)",
		"sys_domain_path":"VarChar(64)",
		"discovery_proto_id":"VarChar(64)",
		"delivery_date":"VarChar(64)",
		"maintenance_schedule":"VarChar(64)",
		"hardware_status":"VarChar(64)",
		"channels":"Integer",
		"install_status":"Integer",
		"cost_center":"VarChar(64)",
		"supported_by":"VarChar(64)",
		"dns_domain":"VarChar(64)",
		"name":"VarChar(64)",
		"assigned":"Timestamp(0)",
		"purchase_date":"VarChar(64)",
		"subcategory":"VarChar(64)",
		"default_gateway":"VarChar(64)",
		"short_description":"VarChar(64)",
		"assignment_group":"VarChar(64)",
		"managed_by":{
			"link":"VarChar(132)",
			"value":"VarChar(64)"
		},
		"range":"Integer",
		"firmware_version":"VarChar(64)",
		"can_print":"VarChar(64)",
		"last_discovered":"VarChar(64)",
		"ports":"Integer",
		"sys_class_name":"VarChar(64)",
		"can_hub":"VarChar(64)",
		"cpu_count":"Integer",
		"manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"sys_id":"VarChar(64)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(64)",
		"mac_address":"VarChar(64)",
		"vendor":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"can_route":"VarChar(64)",
		"company":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":"VarChar(64)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"snmp_sys_location":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"Double",
		"bandwidth":"Integer",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(64)",
		"serial_number":"VarChar(64)",
		"ip_address":"VarChar(64)",
		"model_id":{
			"link":"VarChar(135)",
			"value":"VarChar(64)"
		},
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(64)",
		"discovery_proto_type":"VarChar(64)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"support_group":"VarChar(64)",
		"due":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(64)",
		"attributes":"VarChar(64)",
		"location":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"asset":{
			"link":"VarChar(133)",
			"value":"VarChar(64)"
		},
		"category":"VarChar(64)",
		"fault_count":"Integer",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_ci_server":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_server /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"firewall_status":"VarChar(64)",
		"os_address_width":"VarChar(64)",
		"operational_status":"Integer,#key",
		"os_service_pack":"VarChar(64)",
		"cpu_core_thread":"VarChar(64)",
		"cpu_manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"sys_updated_on":"Timestamp(0)",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"due_in":"VarChar(64)",
		"used_for":"VarChar(64)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(16)",
		"ram":"Integer",
		"warranty_expiration":"Date",
		"cpu_name":"VarChar(64)",
		"cpu_speed":"Integer",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"classification":"VarChar(64)",
		"disk_space":"Double",
		"sys_domain_path":"VarChar(1)",
		"object_id":"VarChar(64)",
		"maintenance_schedule":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"cost_center":{
			"link":"VarChar(142)",
			"value":"VarChar(64)"
		},
		"dns_domain":"VarChar(64)",
		"assigned":"Timestamp(0)",
		"purchase_date":"VarChar(64)",
		"cd_speed":"Integer",
		"short_description":"VarChar(105)",
		"floppy":"VarChar(64)",
		"managed_by":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"os_domain":"VarChar(64)",
		"can_print":"VarChar(7)",
		"last_discovered":"VarChar(64)",
		"sys_class_name":"VarChar(30)",
		"cpu_count":"Integer",
		"manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"vendor":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"model_number":"VarChar(64)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"os_version":"VarChar(64)",
		"serial_number":"VarChar(64)",
		"cd_rom":"VarChar(7)",
		"support_group":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(7)",
		"attributes":"VarChar(64)",
		"asset":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"cpu_core_count":"VarChar(64)",
		"form_factor":"VarChar(64)",
		"skip_sync":"VarChar(7)",
		"sys_updated_by":"VarChar(9)",
		"sys_created_on":"Timestamp(0)",
		"cpu_type":"VarChar(48)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(9)"
		},
		"install_date":"Timestamp(0)",
		"asset_tag":"VarChar(12)",
		"dr_backup":"VarChar(64)",
		"hardware_substatus":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"delivery_date":"VarChar(64)",
		"hardware_status":"VarChar(64)",
		"install_status":"Integer",
		"supported_by":"VarChar(64)",
		"name":"VarChar(49)",
		"subcategory":"VarChar(64)",
		"default_gateway":"VarChar(64)",
		"chassis_type":"VarChar(64)",
		"virtual":"VarChar(7)",
		"assignment_group":"VarChar(64)",
		"sys_id":"VarChar(48)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(27)",
		"mac_address":"VarChar(64)",
		"company":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"justification":"VarChar(64)",
		"department":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"Double",
		"os":"VarChar(31)",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(7)",
		"ip_address":"VarChar(64)",
		"model_id":{
			"link":"VarChar(135)",
			"value":"VarChar(48)"
		},
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(4)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"due":"VarChar(64)",
		"location":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"category":"VarChar(34)",
		"fault_count":"Integer",
		"host_name":"VarChar(64)",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_ci_spkg":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_spkg /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"skip_sync":"VarChar(7),#key",
		"operational_status":"Integer",
		"sys_updated_on":"Timestamp(0)",
		"install_count":"Integer",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"sys_updated_by":"VarChar(9)",
		"due_in":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(9)"
		},
		"install_date":"VarChar(64)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(19)",
		"part_of":"VarChar(64)",
		"warranty_expiration":"VarChar(64)",
		"asset_tag":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"license_count":"Integer",
		"change_control":"VarChar(64)",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"sys_domain_path":"VarChar(1)",
		"version":"VarChar(43)",
		"delivery_date":"VarChar(64)",
		"maintenance_schedule":"VarChar(64)",
		"install_status":"Integer",
		"cost_center":"VarChar(64)",
		"supported_by":"VarChar(64)",
		"dns_domain":"VarChar(64)",
		"name":"VarChar(103)",
		"assigned":"VarChar(64)",
		"purchase_date":"VarChar(64)",
		"subcategory":"VarChar(64)",
		"short_description":"VarChar(64)",
		"assignment_group":"VarChar(64)",
		"managed_by":"VarChar(64)",
		"can_print":"VarChar(7)",
		"last_discovered":"VarChar(64)",
		"sys_class_name":"VarChar(18)",
		"manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"sys_id":"VarChar(48)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(9)",
		"mac_address":"VarChar(64)",
		"vendor":"VarChar(64)",
		"company":"VarChar(64)",
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":"VarChar(64)",
		"key":"VarChar(133)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"msft_sms_id":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"VarChar(64)",
		"license_available":"Integer",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(7)",
		"serial_number":"VarChar(64)",
		"ip_address":"VarChar(64)",
		"model_id":"VarChar(64)",
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(64)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"support_group":"VarChar(64)",
		"due":"VarChar(64)",
		"package_name":"VarChar(127)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(7)",
		"attributes":"VarChar(64)",
		"location":"VarChar(64)",
		"asset":"VarChar(64)",
		"category":"VarChar(64)",
		"fault_count":"Integer",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_unix_server":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_unix_server /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"firewall_status":"VarChar(64),#key",
		"os_address_width":"VarChar(64)",
		"operational_status":"Integer",
		"os_service_pack":"VarChar(64)",
		"cpu_core_thread":"VarChar(64)",
		"cpu_manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"sys_updated_on":"Timestamp(0)",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"due_in":"VarChar(64)",
		"used_for":"VarChar(64)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(64)",
		"ram":"Integer",
		"warranty_expiration":"VarChar(64)",
		"cpu_name":"VarChar(64)",
		"cpu_speed":"Integer",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"classification":"VarChar(64)",
		"disk_space":"Integer",
		"sys_domain_path":"VarChar(64)",
		"object_id":"VarChar(64)",
		"maintenance_schedule":"VarChar(64)",
		"cost_center":{
			"link":"VarChar(142)",
			"value":"VarChar(64)"
		},
		"dns_domain":"VarChar(64)",
		"assigned":"Timestamp(0)",
		"purchase_date":"VarChar(64)",
		"cd_speed":"VarChar(64)",
		"short_description":"VarChar(64)",
		"floppy":"VarChar(64)",
		"managed_by":{
			"link":"VarChar(132)",
			"value":"VarChar(64)"
		},
		"os_domain":"VarChar(64)",
		"can_print":"VarChar(64)",
		"last_discovered":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"cpu_count":"Integer",
		"manufacturer":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"vendor":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"model_number":"VarChar(64)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"os_version":"VarChar(64)",
		"serial_number":"VarChar(64)",
		"cd_rom":"VarChar(64)",
		"support_group":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(64)",
		"attributes":"VarChar(64)",
		"asset":{
			"link":"VarChar(133)",
			"value":"VarChar(64)"
		},
		"cpu_core_count":"VarChar(64)",
		"form_factor":"VarChar(64)",
		"skip_sync":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"cpu_type":"VarChar(64)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(64)"
		},
		"install_date":"Timestamp(0)",
		"asset_tag":"VarChar(64)",
		"dr_backup":"VarChar(64)",
		"hardware_substatus":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"delivery_date":"VarChar(64)",
		"hardware_status":"VarChar(64)",
		"install_status":"Integer",
		"supported_by":"VarChar(64)",
		"name":"VarChar(64)",
		"subcategory":"VarChar(64)",
		"default_gateway":"VarChar(64)",
		"chassis_type":"VarChar(64)",
		"virtual":"VarChar(64)",
		"assignment_group":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(64)",
		"mac_address":"VarChar(64)",
		"company":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"justification":"VarChar(64)",
		"department":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"Double",
		"os":"VarChar(64)",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(64)",
		"ip_address":"VarChar(64)",
		"model_id":{
			"link":"VarChar(135)",
			"value":"VarChar(64)"
		},
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(64)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"due":"VarChar(64)",
		"location":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"category":"VarChar(64)",
		"fault_count":"Integer",
		"host_name":"VarChar(64)",
		"lease_id":"VarChar(64)"
	},
	"TABLE_Cmdb_CI_ci_vm":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_vm /result"
		]
	},
	"TABLE_Cmdb_CI_web_server":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_ci_web_server /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"tcp_port":"VarChar(64)",
		"skip_sync":"VarChar(64),#key",
		"operational_status":"Integer",
		"running_process_command":"VarChar(64)",
		"pid":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"type":"VarChar(64)",
		"running_process_key_parameters":"VarChar(64)",
		"rp_command_hash":"VarChar(64)",
		"discovery_source":"VarChar(64)",
		"first_discovered":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"due_in":"VarChar(64)",
		"install_directory":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(64)"
		},
		"used_for":"VarChar(64)",
		"install_date":"VarChar(64)",
		"is_clustered":"VarChar(64)",
		"gl_account":"VarChar(64)",
		"invoice_number":"VarChar(64)",
		"sys_created_by":"VarChar(64)",
		"warranty_expiration":"VarChar(64)",
		"asset_tag":"VarChar(64)",
		"fqdn":"VarChar(64)",
		"change_control":"VarChar(64)",
		"owned_by":"VarChar(64)",
		"checked_out":"VarChar(64)",
		"rp_key_parameters_hash":"VarChar(64)",
		"sys_domain_path":"VarChar(64)",
		"version":"Double",
		"delivery_date":"VarChar(64)",
		"maintenance_schedule":"VarChar(64)",
		"install_status":"Integer",
		"cost_center":"VarChar(64)",
		"supported_by":"VarChar(64)",
		"dns_domain":"VarChar(64)",
		"name":"VarChar(64)",
		"provided_by":"VarChar(64)",
		"assigned":"VarChar(64)",
		"purchase_date":"VarChar(64)",
		"subcategory":"VarChar(64)",
		"short_description":"VarChar(64)",
		"assignment_group":"VarChar(64)",
		"managed_by":"VarChar(64)",
		"edition":"VarChar(64)",
		"can_print":"VarChar(64)",
		"last_discovered":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"manufacturer":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"po_number":"VarChar(64)",
		"checked_in":"VarChar(64)",
		"sys_class_path":"VarChar(64)",
		"mac_address":"VarChar(64)",
		"vendor":"VarChar(64)",
		"company":"VarChar(64)",
		"justification":"VarChar(64)",
		"model_number":"VarChar(64)",
		"department":"VarChar(64)",
		"config_file":"VarChar(64)",
		"assigned_to":"VarChar(64)",
		"start_date":"VarChar(64)",
		"comments":"VarChar(64)",
		"cost":"VarChar(64)",
		"sys_mod_count":"Integer",
		"monitor":"VarChar(64)",
		"serial_number":"VarChar(64)",
		"ip_address":"VarChar(64)",
		"model_id":"VarChar(64)",
		"sys_tags":"VarChar(64)",
		"cost_cc":"VarChar(64)",
		"order_date":"VarChar(64)",
		"schedule":"VarChar(64)",
		"support_group":{
			"link":"VarChar(141)",
			"value":"VarChar(64)"
		},
		"due":"VarChar(64)",
		"correlation_id":"VarChar(64)",
		"unverified":"VarChar(64)",
		"attributes":"VarChar(64)",
		"location":"VarChar(64)",
		"asset":{
			"link":"VarChar(133)",
			"value":"VarChar(64)"
		},
		"category":"VarChar(64)",
		"fault_count":"Integer",
		"config_directory":"VarChar(64)",
		"lease_id":"VarChar(64)"
	},
	"TABLE_CmdbMetric":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/cmdb_metric"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"error":{
			"detail":"VarChar(64)",
			"message":"VarChar(64),#key"
		},
		"status":"VarChar(64)"
	},
	"TABLE_DiagrammerAction":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/diagrammer_action /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"icon":"VarChar(64)",
		"sys_mod_count":"Integer,#key",
		"active":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"sys_tags":"VarChar(64)",
		"type":"VarChar(64)",
		"script":"VarChar(1579)",
		"sys_class_name":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(64)"
		},
		"condition":"VarChar(348)",
		"sys_update_name":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"name":"VarChar(64)",
		"sys_name":"VarChar(64)",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(64)"
		},
		"sys_created_by":"VarChar(64)",
		"order":"Integer",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_DiscoveryProbes":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/discovery_probes /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"used_by_runbook":"VarChar(7),#key",
		"classic_mode":"VarChar(7)",
		"cache_results":"VarChar(7)",
		"description":"VarChar(903)",
		"host_classification":"VarChar(7)",
		"sys_updated_on":"Timestamp(0)",
		"type":"VarChar(6)",
		"sys_class_name":"VarChar(33)",
		"minor_version":"Integer",
		"ecc_queue_source":"VarChar(64)",
		"sys_id":"VarChar(48)",
		"sys_updated_by":"VarChar(24)",
		"sys_created_on":"Timestamp(0)",
		"used_by_discovery":"VarChar(7)",
		"sys_name":"VarChar(54)",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(9)"
		},
		"sys_created_by":"VarChar(21)",
		"ecc_queue_topic":"VarChar(22)",
		"sys_mod_count":"Integer",
		"sys_tags":"VarChar(64)",
		"post_processor_script":"LongVarChar(21345)",
		"script":"VarChar(64)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"major_version":"Integer",
		"sys_update_name":"VarChar(82)",
		"ecc_queue_name":"VarChar(117)",
		"name":"VarChar(54)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_Ecc_AGENT_agent_metric":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/ecc_agent_metric /result"
		]
	},
	"TABLE_ExpertPanel":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/expert_panel /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"expert":{
			"link":"VarChar(129)",
			"value":"VarChar(64),#key"
		},
		"next_message":"VarChar(64)",
		"previous_message":"VarChar(64)",
		"banner_step":"VarChar(64)",
		"sys_mod_count":"Integer",
		"description":"VarChar(435)",
		"sys_updated_on":"Timestamp(0)",
		"sys_tags":"VarChar(64)",
		"title":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(64)"
		},
		"sys_update_name":"VarChar(82)",
		"sys_updated_by":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"name":"VarChar(64)",
		"sys_name":"VarChar(64)",
		"complete_message":"VarChar(64)",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(64)"
		},
		"sys_created_by":"VarChar(64)",
		"order":"VarChar(64)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_ProcessStep":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/process_step /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"sys_mod_count":"Integer,#key",
		"sys_updated_on":"Timestamp(0)",
		"sys_tags":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(64)"
		},
		"sys_update_name":"VarChar(81)",
		"sys_updated_by":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"name":"VarChar(64)",
		"sys_name":"VarChar(64)",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(64)"
		},
		"process_guide":{
			"link":"VarChar(139)",
			"value":"VarChar(64)"
		},
		"sys_created_by":"VarChar(64)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_Item_OPTION_option_new":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/item_option_new /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"instructions":"VarChar(64)",
		"lookup_label":"VarChar(64)",
		"dynamic_ref_qual":{
			"link":"VarChar(157)",
			"value":"VarChar(64),#key"
		},
		"rec_lookup_price":"VarChar(64)",
		"rec_price_if_checked":"Integer",
		"choice_field":"VarChar(64)",
		"display_title":"VarChar(7)",
		"tooltip":"VarChar(64)",
		"show_help_on_load":"VarChar(7)",
		"sys_updated_on":"Timestamp(0)",
		"type":"Integer",
		"ui_page":"VarChar(64)",
		"reference":"VarChar(39)",
		"sys_updated_by":"VarChar(21)",
		"lookup_table":"VarChar(64)",
		"lookup_value":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"record":"VarChar(64)",
		"mask_use_confirmation":"VarChar(7)",
		"sys_name":"VarChar(136)",
		"reference_qual_condition":"VarChar(85)",
		"sys_created_by":"VarChar(19)",
		"order":"Integer",
		"map_to_field":"VarChar(7)",
		"choice_direction":"VarChar(9)",
		"visibility":"Integer",
		"delivery_plan":{
			"link":"VarChar(157)",
			"value":"VarChar(64)"
		},
		"delete_roles":"VarChar(64)",
		"active":"VarChar(7)",
		"choice_table":"VarChar(64)",
		"sys_update_name":"VarChar(72)",
		"field":"VarChar(33)",
		"name":"VarChar(48)",
		"variable_width":"Integer",
		"help_text":"VarChar(1171)",
		"sys_policy":"VarChar(64)",
		"use_dynamic_default":"VarChar(7)",
		"description":"VarChar(1546)",
		"global":"VarChar(7)",
		"scale_min":"Integer",
		"show_help":"VarChar(7)",
		"mandatory":"VarChar(7)",
		"visible_guide":"VarChar(6)",
		"visible_standalone":"VarChar(6)",
		"sys_class_name":"VarChar(22)",
		"do_not_select_first":"VarChar(7)",
		"dynamic_default_value":"VarChar(64)",
		"sys_id":"VarChar(48)",
		"example_text":"VarChar(64)",
		"variable_set":{
			"link":"VarChar(148)",
			"value":"VarChar(64)"
		},
		"write_roles":"VarChar(64)",
		"pricing_implications":"VarChar(7)",
		"read_roles":"VarChar(64)",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(9)"
		},
		"visible_bundle":"VarChar(6)",
		"variable_name":"VarChar(64)",
		"create_roles":"VarChar(64)",
		"list_table":"VarChar(64)",
		"sp_widget":{
			"link":"VarChar(133)",
			"value":"VarChar(64)"
		},
		"table":"VarChar(64)",
		"macro":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"use_reference_qualifier":"VarChar(12)",
		"mask_use_encryption":"VarChar(7)",
		"include_none":"VarChar(7)",
		"sys_mod_count":"Integer",
		"visible_summary":"VarChar(7)",
		"lookup_price":"VarChar(64)",
		"default_value":"VarChar(202)",
		"price_if_checked":"Integer",
		"sys_tags":"VarChar(64)",
		"help_tag":"VarChar(24)",
		"layout":"VarChar(10)",
		"question_text":"VarChar(136)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"summary_macro":"VarChar(64)",
		"cat_item":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"record_producer_table":"VarChar(37)",
		"scale_max":"Integer",
		"attributes":"VarChar(64)",
		"category":"VarChar(64)",
		"lookup_unique":"VarChar(7)",
		"reference_qual":"VarChar(268)",
		"default_html_value":"VarChar(1038)"
	},
	"TABLE_Question":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/question /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"lookup_label":"VarChar(64)",
		"dynamic_ref_qual":{
			"link":"VarChar(157)",
			"value":"VarChar(64),#key"
		},
		"rec_lookup_price":"VarChar(64)",
		"rec_price_if_checked":"Integer",
		"choice_field":"VarChar(64)",
		"display_title":"VarChar(7)",
		"tooltip":"VarChar(64)",
		"show_help_on_load":"VarChar(7)",
		"sys_updated_on":"Timestamp(0)",
		"type":"Integer",
		"ui_page":"VarChar(64)",
		"reference":"VarChar(39)",
		"sys_updated_by":"VarChar(21)",
		"lookup_table":"VarChar(64)",
		"lookup_value":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"record":"VarChar(64)",
		"mask_use_confirmation":"VarChar(7)",
		"sys_name":"VarChar(136)",
		"reference_qual_condition":"VarChar(85)",
		"sys_created_by":"VarChar(19)",
		"order":"Integer",
		"map_to_field":"VarChar(7)",
		"choice_direction":"VarChar(9)",
		"delete_roles":"VarChar(64)",
		"active":"VarChar(7)",
		"choice_table":"VarChar(64)",
		"sys_update_name":"VarChar(72)",
		"field":"VarChar(33)",
		"name":"VarChar(48)",
		"help_text":"VarChar(1171)",
		"sys_policy":"VarChar(64)",
		"use_dynamic_default":"VarChar(7)",
		"scale_min":"Integer",
		"show_help":"VarChar(7)",
		"mandatory":"VarChar(7)",
		"sys_class_name":"VarChar(22)",
		"do_not_select_first":"VarChar(7)",
		"dynamic_default_value":"VarChar(64)",
		"sys_id":"VarChar(48)",
		"example_text":"VarChar(64)",
		"write_roles":"VarChar(64)",
		"pricing_implications":"VarChar(7)",
		"read_roles":"VarChar(64)",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(9)"
		},
		"variable_name":"VarChar(64)",
		"create_roles":"VarChar(64)",
		"list_table":"VarChar(64)",
		"table":"VarChar(64)",
		"macro":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"use_reference_qualifier":"VarChar(12)",
		"mask_use_encryption":"VarChar(7)",
		"include_none":"VarChar(7)",
		"sys_mod_count":"Integer",
		"lookup_price":"VarChar(64)",
		"default_value":"VarChar(202)",
		"price_if_checked":"Integer",
		"sys_tags":"VarChar(64)",
		"help_tag":"VarChar(24)",
		"layout":"VarChar(10)",
		"question_text":"VarChar(136)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"summary_macro":"VarChar(64)",
		"record_producer_table":"VarChar(37)",
		"scale_max":"Integer",
		"attributes":"VarChar(64)",
		"lookup_unique":"VarChar(7)",
		"reference_qual":"VarChar(268)",
		"default_html_value":"VarChar(1038)"
	},
	"TABLE_Sc_CAT_cat_item":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sc_cat_item /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"entitlement_script":"VarChar(64)",
		"use_sc_layout":"VarChar(7),#key",
		"show_variable_help_on_load":"VarChar(7)",
		"no_order_now":"VarChar(7)",
		"sc_ic_version":"VarChar(64)",
		"delivery_time":"Timestamp(0)",
		"sys_updated_on":"Timestamp(0)",
		"type":"VarChar(6)",
		"no_search":"VarChar(7)",
		"sys_updated_by":"VarChar(25)",
		"price":"Double",
		"sys_created_on":"Timestamp(0)",
		"recurring_frequency":"VarChar(64)",
		"sys_name":"VarChar(64)",
		"model":{
			"link":"VarChar(135)",
			"value":"VarChar(64)"
		},
		"no_cart":"VarChar(7)",
		"sys_created_by":"VarChar(28)",
		"group":"VarChar(64)",
		"hide_sp":"VarChar(7)",
		"order":"Integer",
		"start_closed":"VarChar(7)",
		"image":"VarChar(64)",
		"no_quantity":"VarChar(7)",
		"workflow":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"delivery_plan":{
			"link":"VarChar(157)",
			"value":"VarChar(48)"
		},
		"active":"VarChar(7)",
		"custom_cart":"VarChar(64)",
		"no_proceed_checkout":"VarChar(7)",
		"ignore_price":"VarChar(7)",
		"sys_update_name":"VarChar(88)",
		"meta":"VarChar(64)",
		"omit_price":"VarChar(7)",
		"name":"VarChar(64)",
		"mobile_hide_price":"VarChar(7)",
		"sys_policy":"VarChar(64)",
		"preview":"VarChar(282)",
		"template":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"short_description":"VarChar(280)",
		"roles":"VarChar(64)",
		"icon":"VarChar(64)",
		"description":"VarChar(2964)",
		"mobile_picture":"VarChar(64)",
		"availability":"VarChar(15)",
		"visible_guide":"VarChar(6)",
		"visible_standalone":"VarChar(7)",
		"sys_class_name":"VarChar(39)",
		"sys_id":"VarChar(48)",
		"no_order":"VarChar(7)",
		"vendor":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"mobile_picture_type":"VarChar(28)",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(9)"
		},
		"visible_bundle":"VarChar(6)",
		"sc_catalogs":"VarChar(97)",
		"ordered_item_link":"VarChar(64)",
		"cost":"Double",
		"sys_mod_count":"Integer",
		"recurring_price":"Integer",
		"list_price":"Integer",
		"sc_ic_item_staging":"VarChar(64)",
		"sys_tags":"VarChar(64)",
		"billable":"VarChar(7)",
		"picture":"VarChar(64)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"delivery_plan_script":"VarChar(628)",
		"location":"VarChar(64)",
		"category":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		}
	},
	"TABLE_Sc_CAT_ITEM_delivery_task":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sc_cat_item_delivery_task /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"instructions":"VarChar(402)",
		"short_description":"VarChar(93)",
		"condition_script":"VarChar(253)",
		"delivery_time":"Timestamp(0),#key",
		"generation_script":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"sys_class_name":"VarChar(37)",
		"sys_id":"VarChar(48)",
		"sys_updated_by":"VarChar(16)",
		"sys_created_on":"Timestamp(0)",
		"sys_name":"VarChar(46)",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(9)"
		},
		"sys_created_by":"VarChar(16)",
		"assigned_to":"VarChar(64)",
		"group":{
			"link":"VarChar(141)",
			"value":"VarChar(48)"
		},
		"order":"Integer",
		"delivery_plan":{
			"link":"VarChar(157)",
			"value":"VarChar(48)"
		},
		"sys_mod_count":"Integer",
		"sla":"VarChar(64)",
		"sys_tags":"VarChar(64)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"condition":"VarChar(85)",
		"sys_update_name":"VarChar(87)",
		"name":"VarChar(46)",
		"work_notes":"VarChar(64)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_ScCategory":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sc_category /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"homepage_renderer":{
			"link":"VarChar(150)",
			"value":"VarChar(48),#key"
		},
		"parent":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"entitlement_script":"VarChar(64)",
		"mobile_subcategory_render_type":"VarChar(6)",
		"mobile_hide_description":"VarChar(7)",
		"roles":"VarChar(40)",
		"icon":"VarChar(64)",
		"description":"VarChar(499)",
		"mobile_picture":"VarChar(64)",
		"sc_catalog":{
			"link":"VarChar(135)",
			"value":"VarChar(48)"
		},
		"sys_updated_on":"Timestamp(0)",
		"title":"VarChar(46)",
		"sys_class_name":"VarChar(25)",
		"sys_id":"VarChar(48)",
		"sys_updated_by":"VarChar(19)",
		"homepage_image":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_name":"VarChar(46)",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(9)"
		},
		"sys_created_by":"VarChar(19)",
		"order":"Integer",
		"image":"VarChar(64)",
		"header_icon":"VarChar(64)",
		"module":{
			"link":"VarChar(141)",
			"value":"VarChar(64)"
		},
		"sys_mod_count":"Integer",
		"active":"VarChar(7)",
		"sys_tags":"VarChar(64)",
		"show_in_cms":"VarChar(7)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"sys_update_name":"VarChar(75)",
		"location":"VarChar(64)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_Scheduled_DATA_data_import":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/scheduled_data_import /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"parent":{
			"link":"VarChar(151)",
			"value":"VarChar(64),#key"
		},
		"conditional":"VarChar(64)",
		"run_as_tz":"VarChar(64)",
		"post_script":"VarChar(64)",
		"run_as":{
			"link":"VarChar(100)",
			"value":"VarChar(64)"
		},
		"run_type":"VarChar(64)",
		"sys_updated_on":"Timestamp(0)",
		"sys_class_name":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"post_script_bool":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"run_start":"VarChar(64)",
		"sys_name":"VarChar(64)",
		"run_dayofmonth":"Integer",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(64)"
		},
		"map":{
			"link":"VarChar(139)",
			"value":"VarChar(64)"
		},
		"run_dayofweek":"Integer",
		"sys_created_by":"VarChar(64)",
		"order":"VarChar(64)",
		"upgrade_safe":"VarChar(64)",
		"pre_script":"VarChar(64)",
		"run_time":"Timestamp(0)",
		"sys_mod_count":"Integer",
		"active":"VarChar(64)",
		"pre_script_bool":"VarChar(64)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(64)"
		},
		"condition":"VarChar(64)",
		"sys_update_name":"VarChar(81)",
		"name":"VarChar(64)",
		"run_period":"VarChar(64)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_Sla":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sla /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"responsible_user":"VarChar(64)",
		"short_description":"VarChar(64)",
		"incident_procedures":"VarChar(64)",
		"notes":"VarChar(64)",
		"security_notes":"VarChar(64)",
		"technical_lead":"VarChar(64)",
		"change_procedures":"VarChar(64)",
		"description":"VarChar(64)",
		"consultant_user":"VarChar(64)",
		"sys_updated_on":"Timestamp(0),#key",
		"signatures":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"begins":"Date",
		"avail_pct":"Double",
		"number":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"ends":"Date",
		"department":"VarChar(64)",
		"sys_created_by":"VarChar(64)",
		"calendar":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"disaster_recovery":"VarChar(64)",
		"contract":"VarChar(64)",
		"sys_mod_count":"Integer",
		"active":"VarChar(64)",
		"service_goals":"VarChar(64)",
		"sys_tags":"VarChar(64)",
		"business_unit":"VarChar(64)",
		"informed_user":"VarChar(64)",
		"functional_area":"VarChar(64)",
		"users":"VarChar(64)",
		"business_lead":"VarChar(64)",
		"transaction_load":"VarChar(64)",
		"reponsibilities":"VarChar(64)",
		"name":"VarChar(64)",
		"response_time":"Double",
		"maintenance":"VarChar(64)",
		"next_review":"VarChar(64)",
		"accountable_user":"VarChar(64)"
	},
	"TABLE_SysDictionary":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sys_dictionary /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"calculation":"VarChar(1174)",
		"dynamic_ref_qual":{
			"link":"VarChar(157)",
			"value":"VarChar(48),#key"
		},
		"choice_field":"VarChar(27)",
		"function_field":"VarChar(7)",
		"sys_updated_on":"Timestamp(0)",
		"spell_check":"VarChar(7)",
		"reference_cascade_rule":"VarChar(27)",
		"reference":{
			"link":"VarChar(148)",
			"value":"VarChar(49)"
		},
		"sys_updated_by":"VarChar(21)",
		"read_only":"VarChar(7)",
		"sys_created_on":"Timestamp(0)",
		"array_denormalized":"VarChar(7)",
		"element_reference":"VarChar(7)",
		"sys_name":"VarChar(106)",
		"reference_key":"VarChar(64)",
		"reference_qual_condition":"VarChar(166)",
		"xml_view":"VarChar(7)",
		"dependent":"VarChar(57)",
		"internal_type":{
			"link":"VarChar(132)",
			"value":"VarChar(28)"
		},
		"sys_created_by":"VarChar(24)",
		"element":"VarChar(73)",
		"max_length":"Integer",
		"use_dependent_field":"VarChar(7)",
		"delete_roles":"VarChar(79)",
		"active":"VarChar(6)",
		"choice_table":"VarChar(34)",
		"foreign_database":"VarChar(64)",
		"sys_update_name":"VarChar(142)",
		"unique":"VarChar(7)",
		"name":"VarChar(106)",
		"dependent_on_field":"VarChar(57)",
		"dynamic_creation":"VarChar(7)",
		"primary":"VarChar(7)",
		"sys_policy":"VarChar(6)",
		"next_element":"VarChar(64)",
		"virtual":"VarChar(7)",
		"widget":"VarChar(64)",
		"use_dynamic_default":"VarChar(7)",
		"sizeclass":"Integer",
		"mandatory":"VarChar(7)",
		"sys_class_name":"VarChar(46)",
		"dynamic_default_value":{
			"link":"VarChar(157)",
			"value":"VarChar(48)"
		},
		"sys_id":"VarChar(48)",
		"write_roles":"VarChar(79)",
		"array":"VarChar(7)",
		"audit":"VarChar(7)",
		"read_roles":"VarChar(48)",
		"sys_scope":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"create_roles":"VarChar(31)",
		"dynamic_creation_script":"VarChar(64)",
		"defaultsort":"Integer",
		"column_label":"VarChar(72)",
		"comments":"VarChar(64)",
		"use_reference_qualifier":"VarChar(12)",
		"display":"VarChar(7)",
		"reference_floats":"VarChar(7)",
		"sys_mod_count":"Integer",
		"default_value":"VarChar(2565)",
		"staged":"VarChar(7)",
		"reference_type":"VarChar(64)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"attributes":"VarChar(351)",
		"choice":"Integer",
		"reference_qual":"VarChar(265)",
		"table_reference":"VarChar(7)",
		"text_index":"VarChar(7)",
		"function_definition":"VarChar(64)"
	},
	"TABLE_Sys_IMPORT_set_row":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sys_import_set_row /result"
		]
	},
	"TABLE_Sys_script_client":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sys_script_client /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"isolate_script":"VarChar(7),#key",
		"applies_extended":"VarChar(7)",
		"description":"VarChar(649)",
		"global":"VarChar(7)",
		"sys_updated_on":"Timestamp(0)",
		"type":"VarChar(15)",
		"sys_class_name":"VarChar(31)",
		"sys_id":"VarChar(48)",
		"ui_type":"Integer",
		"view":"VarChar(64)",
		"sys_updated_by":"VarChar(31)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(9)"
		},
		"sys_name":"VarChar(72)",
		"sys_scope":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"sys_created_by":"VarChar(31)",
		"table":"VarChar(49)",
		"order":"Integer",
		"sys_mod_count":"Integer",
		"active":"VarChar(7)",
		"sys_overrides":{
			"link":"VarChar(106)",
			"value":"VarChar(9)"
		},
		"sys_domain_path":"VarChar(1)",
		"sys_tags":"VarChar(64)",
		"script":"LongVarChar(27688)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"condition":"VarChar(64)",
		"sys_update_name":"VarChar(81)",
		"field":"VarChar(43)",
		"name":"VarChar(60)",
		"messages":"VarChar(670)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_Sys_UI_policy":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sys_ui_policy /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"short_description":"VarChar(210)",
		"set_values":"VarChar(64)",
		"isolate_script":"VarChar(7),#key",
		"description":"VarChar(595)",
		"global":"VarChar(7)",
		"sys_updated_on":"Timestamp(0)",
		"sys_class_name":"VarChar(25)",
		"sys_id":"VarChar(48)",
		"ui_type":"Integer",
		"view":{
			"link":"VarChar(147)",
			"value":"VarChar(64)"
		},
		"sys_updated_by":"VarChar(31)",
		"sys_created_on":"Timestamp(0)",
		"script_true":"VarChar(2530)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(9)"
		},
		"reverse_if_false":"VarChar(7)",
		"sys_name":"VarChar(210)",
		"sys_scope":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"sys_created_by":"VarChar(31)",
		"table":"VarChar(46)",
		"order":"Integer",
		"run_scripts":"VarChar(7)",
		"sys_mod_count":"Integer",
		"active":"VarChar(7)",
		"sys_overrides":"VarChar(64)",
		"model_id":"VarChar(64)",
		"sys_domain_path":"VarChar(1)",
		"sys_tags":"VarChar(64)",
		"script_false":"VarChar(901)",
		"model_table":"VarChar(64)",
		"on_load":"VarChar(7)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"sys_update_name":"VarChar(75)",
		"inherit":"VarChar(7)",
		"conditions":"VarChar(1744)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_Sys_UI_policy_action":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sys_ui_policy_action /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"ui_policy":{
			"link":"VarChar(139)",
			"value":"VarChar(48),#key"
		},
		"visible":"VarChar(9)",
		"sys_mod_count":"Integer",
		"sys_updated_on":"Timestamp(0)",
		"sys_tags":"VarChar(64)",
		"mandatory":"VarChar(9)",
		"sys_class_name":"VarChar(36)",
		"sys_id":"VarChar(48)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"sys_update_name":"VarChar(85)",
		"sys_updated_by":"VarChar(31)",
		"field":"VarChar(118)",
		"sys_created_on":"Timestamp(0)",
		"sys_name":"VarChar(118)",
		"disabled":"VarChar(9)",
		"sys_scope":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"cleared":"VarChar(7)",
		"sys_created_by":"VarChar(31)",
		"table":"VarChar(51)",
		"sys_policy":"VarChar(13)"
	},
	"TABLE_Sysauto":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sysauto /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"conditional":"VarChar(7),#key",
		"run_as_tz":"VarChar(64)",
		"run_as":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"run_type":"VarChar(18)",
		"sys_updated_on":"Timestamp(0)",
		"sys_class_name":"VarChar(33)",
		"sys_id":"VarChar(48)",
		"sys_updated_by":"VarChar(18)",
		"sys_created_on":"Timestamp(0)",
		"run_start":"Timestamp(0)",
		"sys_name":"VarChar(115)",
		"run_dayofmonth":"Integer",
		"sys_scope":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"run_dayofweek":"Integer",
		"sys_created_by":"VarChar(18)",
		"upgrade_safe":"VarChar(7)",
		"run_time":"Timestamp(0)",
		"sys_mod_count":"Integer",
		"active":"VarChar(7)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"condition":"VarChar(243)",
		"sys_update_name":"VarChar(81)",
		"name":"VarChar(115)",
		"run_period":"Timestamp(0)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_SysautoScript":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sysauto_script /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"conditional":"VarChar(7),#key",
		"run_as_tz":"VarChar(64)",
		"run_as":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"run_type":"VarChar(18)",
		"sys_updated_on":"Timestamp(0)",
		"sys_class_name":"VarChar(30)",
		"sys_id":"VarChar(48)",
		"sys_updated_by":"VarChar(18)",
		"sys_created_on":"Timestamp(0)",
		"run_start":"Timestamp(0)",
		"sys_name":"VarChar(115)",
		"run_dayofmonth":"Integer",
		"sys_scope":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"run_dayofweek":"Integer",
		"sys_created_by":"VarChar(18)",
		"upgrade_safe":"VarChar(7)",
		"run_time":"Timestamp(0)",
		"sys_mod_count":"Integer",
		"active":"VarChar(7)",
		"script":"LongVarChar(9025)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"condition":"VarChar(243)",
		"sys_update_name":"VarChar(79)",
		"name":"VarChar(115)",
		"run_period":"Timestamp(0)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_Syslog":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/syslog /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"sys_id":"VarChar(48),#key",
		"level":"Integer",
		"sys_created_on":"Timestamp(0)",
		"source":"VarChar(60)",
		"message":"VarChar(5476)",
		"sys_class_name":"VarChar(25)",
		"sys_created_by":"VarChar(31)"
	},
	"TABLE_Sysrule":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sysrule /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"sys_mod_count":"Integer,#key",
		"description":"VarChar(2368)",
		"sys_overrides":{
			"link":"VarChar(91)",
			"value":"VarChar(64)"
		},
		"sys_updated_on":"Timestamp(0)",
		"sys_domain_path":"VarChar(1)",
		"sys_class_name":"VarChar(36)",
		"sys_id":"VarChar(48)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"sys_update_name":"VarChar(85)",
		"sys_updated_by":"VarChar(31)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(9)"
		},
		"name":"VarChar(60)",
		"sys_name":"VarChar(60)",
		"sys_scope":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"sys_created_by":"VarChar(24)",
		"order":"Integer",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_SysruleEscalate":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/sysrule_escalate /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"description":"VarChar(181)",
		"threshold":"Timestamp(0)",
		"sys_updated_on":"Timestamp(0),#key",
		"pause_condition":"VarChar(64)",
		"sys_class_name":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"sys_updated_by":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(64)"
		},
		"reset_condition":"VarChar(64)",
		"sys_name":"VarChar(64)",
		"sys_scope":{
			"link":"VarChar(94)",
			"value":"VarChar(64)"
		},
		"sys_created_by":"VarChar(64)",
		"table":"VarChar(64)",
		"order":"Integer",
		"calendar":{
			"link":"VarChar(138)",
			"value":"VarChar(64)"
		},
		"assignment_script":"VarChar(64)",
		"sys_mod_count":"Integer",
		"sys_overrides":"VarChar(64)",
		"sys_domain_path":"VarChar(64)",
		"advanced_condition":"VarChar(64)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(64)"
		},
		"condition":"VarChar(73)",
		"sys_update_name":"VarChar(78)",
		"name":"VarChar(64)",
		"sys_policy":"VarChar(64)"
	},
	"TABLE_Task":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/task /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"parent":{
			"link":"VarChar(126)",
			"value":"VarChar(48),#key"
		},
		"made_sla":"VarChar(7)",
		"watch_list":"VarChar(64)",
		"upon_reject":"VarChar(9)",
		"sys_updated_on":"Timestamp(0)",
		"approval_history":"VarChar(64)",
		"number":"VarChar(19)",
		"sys_updated_by":"VarChar(21)",
		"opened_by":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"user_input":"VarChar(64)",
		"sys_created_on":"Timestamp(0)",
		"sys_domain":{
			"link":"VarChar(102)",
			"value":"VarChar(9)"
		},
		"state":"Integer",
		"sys_created_by":"VarChar(19)",
		"knowledge":"VarChar(7)",
		"order":"VarChar(64)",
		"closed_at":"Timestamp(0)",
		"cmdb_ci":{
			"link":"VarChar(130)",
			"value":"VarChar(48)"
		},
		"delivery_plan":"VarChar(64)",
		"impact":"Integer",
		"active":"VarChar(7)",
		"work_notes_list":"VarChar(64)",
		"business_service":{
			"link":"VarChar(142)",
			"value":"VarChar(64)"
		},
		"priority":"Integer",
		"sys_domain_path":"VarChar(1)",
		"time_worked":"VarChar(64)",
		"expected_start":"Timestamp(0)",
		"opened_at":"Timestamp(0)",
		"business_duration":"Timestamp(0)",
		"group_list":"VarChar(64)",
		"work_end":"Timestamp(0)",
		"approval_set":"Timestamp(0)",
		"work_notes":"VarChar(64)",
		"short_description":"VarChar(136)",
		"correlation_display":"VarChar(64)",
		"delivery_task":"VarChar(64)",
		"work_start":"Timestamp(0)",
		"assignment_group":{
			"link":"VarChar(141)",
			"value":"VarChar(48)"
		},
		"additional_assignee_list":"VarChar(64)",
		"description":"VarChar(415)",
		"calendar_duration":"Timestamp(0)",
		"close_notes":"VarChar(73)",
		"sys_class_name":"VarChar(28)",
		"closed_by":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"follow_up":"VarChar(64)",
		"sys_id":"VarChar(48)",
		"contact_type":"VarChar(18)",
		"urgency":"Integer",
		"company":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		},
		"reassignment_count":"Integer",
		"activity_due":"Timestamp(0)",
		"assigned_to":{
			"link":"VarChar(132)",
			"value":"VarChar(48)"
		},
		"comments":"VarChar(64)",
		"approval":"VarChar(19)",
		"sla_due":"Timestamp(0)",
		"comments_and_work_notes":"VarChar(64)",
		"due_date":"Timestamp(0)",
		"sys_mod_count":"Integer",
		"sys_tags":"VarChar(64)",
		"escalation":"Integer",
		"upon_approval":"VarChar(10)",
		"correlation_id":"VarChar(64)",
		"location":{
			"link":"VarChar(138)",
			"value":"VarChar(48)"
		}
	},
	"TABLE_V_FIELD_field_creator":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/v_field_creator /result"
		]
	},
	"TABLE_V_FIELD_field_editor":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/v_field_editor /result"
		]
	},
	"TABLE_V_TABLE_table_creator":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/v_table_creator /result"
		]
	},
	"TABLE_V_WS_ws_creator":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/v_ws_creator /result"
		]
	},
	"TABLE_VarDictionary":{
		"#path":[
			"https://dev66303.service-now.com/api/now/table/var_dictionary /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"calculation":"VarChar(184)",
		"dynamic_ref_qual":{
			"link":"VarChar(157)",
			"value":"VarChar(64),#key"
		},
		"choice_field":"VarChar(64)",
		"function_field":"VarChar(7)",
		"sys_updated_on":"Timestamp(0)",
		"spell_check":"VarChar(7)",
		"reference_cascade_rule":"VarChar(64)",
		"reference":{
			"link":"VarChar(139)",
			"value":"VarChar(40)"
		},
		"sys_updated_by":"VarChar(25)",
		"read_only":"VarChar(7)",
		"sys_created_on":"Timestamp(0)",
		"array_denormalized":"VarChar(7)",
		"element_reference":"VarChar(7)",
		"sys_name":"VarChar(106)",
		"reference_key":"VarChar(64)",
		"reference_qual_condition":"VarChar(222)",
		"xml_view":"VarChar(7)",
		"dependent":"VarChar(36)",
		"internal_type":{
			"link":"VarChar(138)",
			"value":"VarChar(34)"
		},
		"sys_created_by":"VarChar(24)",
		"element":"VarChar(54)",
		"max_length":"Integer",
		"order":"Integer",
		"use_dependent_field":"VarChar(7)",
		"delete_roles":"VarChar(64)",
		"active":"VarChar(6)",
		"choice_table":"VarChar(64)",
		"model_table":"VarChar(45)",
		"foreign_database":"VarChar(64)",
		"sys_update_name":"VarChar(96)",
		"hint":"VarChar(382)",
		"unique":"VarChar(7)",
		"name":"VarChar(106)",
		"dependent_on_field":"VarChar(36)",
		"dynamic_creation":"VarChar(7)",
		"primary":"VarChar(7)",
		"sys_policy":"VarChar(6)",
		"next_element":"VarChar(64)",
		"virtual":"VarChar(7)",
		"widget":"VarChar(64)",
		"use_dynamic_default":"VarChar(7)",
		"sizeclass":"VarChar(64)",
		"mandatory":"VarChar(7)",
		"sys_class_name":"VarChar(46)",
		"dynamic_default_value":"VarChar(64)",
		"sys_id":"VarChar(48)",
		"write_roles":"VarChar(64)",
		"array":"VarChar(7)",
		"audit":"VarChar(7)",
		"read_roles":"VarChar(64)",
		"sys_scope":{
			"link":"VarChar(133)",
			"value":"VarChar(48)"
		},
		"create_roles":"VarChar(64)",
		"dynamic_creation_script":"VarChar(64)",
		"defaultsort":"VarChar(64)",
		"column_label":"VarChar(54)",
		"comments":"VarChar(64)",
		"use_reference_qualifier":"VarChar(12)",
		"display":"VarChar(7)",
		"reference_floats":"VarChar(7)",
		"sys_mod_count":"Integer",
		"default_value":"VarChar(4831)",
		"label":"VarChar(54)",
		"model_id":{
			"link":"VarChar(165)",
			"value":"VarChar(48)"
		},
		"staged":"VarChar(7)",
		"sys_tags":"VarChar(64)",
		"reference_type":"VarChar(64)",
		"help":"VarChar(79)",
		"sys_package":{
			"link":"VarChar(136)",
			"value":"VarChar(48)"
		},
		"attributes":"VarChar(286)",
		"choice":"Integer",
		"reference_qual":"VarChar(222)",
		"table_reference":"VarChar(7)",
		"text_index":"VarChar(7)",
		"function_definition":"VarChar(64)"
	},
	"SC_ServiceCatalog_Catalogs":{
		"#path":[
			"https://dev66303.service-now.com/api/sn_sc/v1/servicecatalog/catalogs /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"title":"VarChar(64),#key",
		"sys_id":"VarChar(64)",
		"has_categories":"Boolean",
		"has_items":"Boolean",
		"description":"VarChar(64)",
		"desktop_image":"VarChar(64)"
	},
	"SC_ServiceCatalog_Items":{
		"#path":[
			"https://dev66303.service-now.com/api/sn_sc/v1/servicecatalog/items /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"short_description":"VarChar(87)",
		"kb_article":"VarChar(64)",
		"icon":"VarChar(64)",
		"description":"VarChar(2964)",
		"show_price":"Boolean",
		"type":"VarChar(64),#key",
		"show_quantity":"Boolean",
		"sys_class_name":"VarChar(64)",
		"picture":"VarChar(64)",
		"url":"VarChar(64)",
		"sys_id":"VarChar(64)",
		"content_type":"VarChar(64)",
		"catalogs[1]":{
			"sys_id":"VarChar(64)",
			"title":"VarChar(64)"
		},
		"name":"VarChar(64)",
		"category":{
			"sys_id":"VarChar(64)",
			"title":"VarChar(64)"
		},
		"order":"Integer",
		"recurring_price":"VarChar(64)",
		"local_currency":"VarChar(64)",
		"recurring_price_currency":"VarChar(64)",
		"localized_price":"VarChar(64)",
		"price":"VarChar(64)",
		"recurring_frequency":"VarChar(64)",
		"localized_recurring_price":"VarChar(64)",
		"price_currency":"VarChar(64)"
	},
	"SC_ServiceCatalog_Cart":{
		"#path":[
			"https://dev66303.service-now.com/api/sn_sc/v1/servicecatalog/cart /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"cart_id":"VarChar(64),#key",
		"subtotal_price":"VarChar(64)",
		"subtotal_recurring_frequency":"VarChar(64)",
		"subtotal_recurring_price":"VarChar(64)",
		"total_title":"VarChar(64)",
		"show_subtotal_price":"VarChar(64)",
		"subtotal_title":"VarChar(64)"
	},
	"PA_ScoreCards":{
		"#path":[
			"https://dev66303.service-now.com/api/now/pa/scorecards /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"indicator":{
			"display_value":"VarChar(75)",
			"link":"VarChar(139)",
			"value":"VarChar(64),#key"
		},
		"gap_formatted":"VarChar(64)",
		"benchmarking":"Boolean",
		"frequency_label":"VarChar(64)",
		"changeperc_formatted":"VarChar(64)",
		"direction_label":"VarChar(64)",
		"precision":"Integer",
		"personal_target":"VarChar(64)",
		"description":"VarChar(546)",
		"value_color":"VarChar(64)",
		"uuid":"VarChar(64)",
		"frequency":"Integer",
		"gap":"VarChar(64)",
		"value_unit":"VarChar(64)",
		"indicator_frequency":"Integer",
		"value":"VarChar(64)",
		"indicator_aggregate":"Integer",
		"key":"Boolean",
		"indicator_frequency_label":"VarChar(64)",
		"direction":"Integer",
		"period_title":"VarChar(64)",
		"period":"VarChar(64)",
		"target_formatted":"VarChar(64)",
		"change":"VarChar(64)",
		"gapperc_formatted":"VarChar(64)",
		"realtime_enabled":"Boolean",
		"changeperc":"VarChar(64)",
		"target":"VarChar(64)",
		"unit":{
			"display_value":"VarChar(64)",
			"link":"VarChar(132)",
			"format":"VarChar(64)",
			"type":"VarChar(64)",
			"value":"VarChar(64)"
		},
		"value_formatted":"VarChar(64)",
		"name":"VarChar(75)",
		"formula":"VarChar(177)",
		"gapperc":"VarChar(64)",
		"change_formatted":"VarChar(64)",
		"favorite":"Boolean",
		"personal_target_formatted":"VarChar(64)",
		"facts_table":{
			"name":"VarChar(64)",
			"label":"VarChar(64)"
		},
		"aggregation_field":"VarChar(64)",
		"query":"VarChar(135)"
	},
	"Attachment":{
		"#path":[
			"https://dev66303.service-now.com/api/now/attachment /result"
		],"#maximumPageSize": 1000,"#firstrow": 0,"#pageSizeParameter": "sysparm_limit","#rowOffsetParameter": "sysparm_offset",
		"size_bytes":"Integer,#key",
		"file_name":"VarChar(112)",
		"sys_mod_count":"Integer",
		"average_image_color":"VarChar(10)",
		"image_width":"Integer",
		"sys_updated_on":"Timestamp(0)",
		"sys_tags":"VarChar(64)",
		"table_name":"VarChar(46)",
		"sys_id":"VarChar(48)",
		"image_height":"Integer",
		"sys_updated_by":"VarChar(28)",
		"download_link":"VarChar(133)",
		"content_type":"VarChar(60)",
		"sys_created_on":"Timestamp(0)",
		"size_compressed":"Integer",
		"compressed":"VarChar(7)",
		"state":"VarChar(64)",
		"table_sys_id":"VarChar(48)",
		"chunk_size_bytes":"Integer",
		"sys_created_by":"VarChar(28)"
	}
}