{
	"bingsearch":{
		"#path":[
			"https://api.cognitive.microsoft.com/bing/v7.0/search"
		],
		"#maximumPageSize": 100,"#firstrow": 0,"#pageSizeParameter": "count","#rowOffsetParameter": "offset",
		"q":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"bill gates",
			"#eq":"q"
		},
		"_type":"VarChar(64),#key",
		"queryContext":{
			"originalQuery":"VarChar(64)"
		},
		"webPages":{
			"webSearchUrl":"VarChar(64)",
			"totalEstimatedMatches":"Integer",
			"value<webPages_values>[]":{
				"id":"VarChar(81)",
				"name":"VarChar(87)",
				"url":"VarChar(99)",
				"about<webPages_about>[]":{
					"name":"VarChar(64)"
				},
				"isFamilyFriendly":"Boolean",
				"displayUrl":"VarChar(99)",
				"snippet":"VarChar(571)",
				"snippetAttribution":{
					"license":{
						"name":"VarChar(64)",
						"url":"VarChar(69)"
					},
					"licenseNotice":"VarChar(64)"
				},
				"dateLastCrawled":"Timestamp(9)",
				"language":"VarChar(64)",
				"isNavigational":"Boolean",
				"richCaption":{
					"_type":"VarChar(64)",
					"listItems[]":{
						"items<webPages_items>[]":{
							"text":"VarChar(570)",
							"_type":"VarChar(34)",
							"image":{
								"url":"VarChar(516)",
								"isVideo":"Boolean"
							},
							"dateTimeDisplayText":"VarChar(64)",
							"url":"VarChar(135)"
						}
					}
				}
			}
		},
		"entities":{
			"value[]":{
				"id":"VarChar(81)",
				"contractualRules<entities_contractualrules>[]":{
					"_type":"VarChar(64)",
					"targetPropertyName":"VarChar(64)",
					"mustBeCloseToContent":"Boolean",
					"license":{
						"name":"VarChar(64)",
						"url":"VarChar(69)"
					},
					"licenseNotice":"VarChar(64)",
					"text":"VarChar(64)",
					"url":"VarChar(64)"
				},
				"webSearchUrl":"VarChar(322)",
				"name":"VarChar(64)",
				"url":"VarChar(64)",
				"image":{
					"name":"VarChar(97)",
					"thumbnailUrl":"VarChar(162)",
					"provider<entities_provider>[]":{
						"_type":"VarChar(64)",
						"url":"VarChar(64)"
					},
					"hostPageUrl":"VarChar(112)",
					"width":"Integer",
					"height":"Integer",
					"sourceWidth":"Integer",
					"sourceHeight":"Integer"
				},
				"description":"VarChar(522)",
				"entityPresentationInfo":{
					"entityScenario":"VarChar(64)",
					"entityTypeHints[]":"VarChar(64)",
					"entityTypeDisplayHint":"VarChar(64)"
				},
				"bingId":"GUID"
			}
		},
		"images":{
			"id":"VarChar(75)",
			"readLink":"VarChar(127)",
			"webSearchUrl":"VarChar(94)",
			"isFamilyFriendly":"Boolean",
			"value<images_values>[]":{
				"webSearchUrl":"VarChar(154)",
				"name":"VarChar(94)",
				"thumbnailUrl":"VarChar(103)",
				"datePublished":"Timestamp(9)",
				"contentUrl":"VarChar(225)",
				"hostPageUrl":"VarChar(234)",
				"contentSize":"VarChar(64)",
				"encodingFormat":"VarChar(64)",
				"hostPageDisplayUrl":"VarChar(234)",
				"width":"Integer",
				"height":"Integer",
				"thumbnail":{
					"width":"Integer",
					"height":"Integer"
				}
			}
		},
		"news":{
			"id":"VarChar(72)",
			"readLink":"VarChar(100)",
			"value<news_values>[]":{
				"contractualRules[1]":{
					"_type":"VarChar(64)",
					"text":"VarChar(64)"
				},
				"name":"VarChar(163)",
				"url":"VarChar(220)",
				"image":{
					"contentUrl":"VarChar(241)",
					"thumbnail":{
						"contentUrl":"VarChar(106)",
						"width":"Integer",
						"height":"Integer"
					}
				},
				"description":"VarChar(388)",
				"provider<news_provider>[1]":{
					"_type":"VarChar(64)",
					"name":"VarChar(64)",
					"image":{
						"thumbnail":{
							"contentUrl":"VarChar(106)"
						}
					}
				},
				"datePublished":"Timestamp(9)",
				"category":"VarChar(64)",
				"about<news_about>[]":{
					"readLink":"VarChar(132)",
					"name":"VarChar(64)"
				},
				"mentions<news_mentions>[]":{
					"name":"VarChar(64)"
				},
				"video":{
					"name":"VarChar(127)",
					"thumbnailUrl":"VarChar(106)",
					"thumbnail":{
						"width":"Integer",
						"height":"Integer"
					}
				}
			}
		},
		"relatedSearches":{
			"id":"VarChar(88)",
			"value<relatedSearches_values>[]":{
				"text":"VarChar(64)",
				"displayText":"VarChar(64)",
				"webSearchUrl":"VarChar(84)"
			}
		},
		"videos":{
			"id":"VarChar(75)",
			"readLink":"VarChar(103)",
			"webSearchUrl":"VarChar(70)",
			"isFamilyFriendly":"Boolean",
			"value<videos_values>[]":{
				"webSearchUrl":"VarChar(159)",
				"name":"VarChar(111)",
				"description":"VarChar(525)",
				"thumbnailUrl":"VarChar(103)",
				"datePublished":"Timestamp(9)",
				"publisher<videos_publisher>[1]":{
					"name":"VarChar(100)"
				},
				"isAccessibleForFree":"Boolean",
				"contentUrl":"VarChar(64)",
				"hostPageUrl":"VarChar(64)",
				"encodingFormat":"VarChar(64)",
				"hostPageDisplayUrl":"VarChar(64)",
				"width":"Integer",
				"height":"Integer",
				"duration":"VarChar(64)",
				"embedHtml":"VarChar(199)",
				"allowHttpsEmbed":"Boolean",
				"viewCount":"Integer",
				"thumbnail":{
					"width":"Integer",
					"height":"Integer"
				},
				"allowMobileEmbed":"Boolean",
				"isSuperfresh":"Boolean",
				"motionThumbnailUrl":"VarChar(100)"
			},
			"scenario":"VarChar(64)"
		},
		"rankingResponse":{
			"mainline":{
				"items<rankingResponse_mainlineitems>[]":{
					"answerType":"VarChar(64)",
					"value":{
						"id":"VarChar(88)"
					},
					"resultIndex":"Integer"
				}
			},
			"sidebar":{
				"items<rankingResponse_sidelineitems>[]":{
					"answerType":"VarChar(64)",
					"value":{
						"id":"VarChar(81)"
					},
					"resultIndex":"Integer"
				}
			}
		},
		"mkt":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"en-us",
			"#eq":"mkt"
		},
		"safesearch":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"Moderate",
			"#eq":"safesearch"
		}
	}
}