SELECT * FROM AUTOREST.BINGSEARCH
SELECT * FROM AUTOREST.BINGSEARCH WHERE Q='Progress Software'

SELECT * FROM AUTOREST.WEBPAGES_VALUES WHERE BINGSEARCH_Q='Microsoft'
SELECT * FROM AUTOREST.WEBPAGES_ABOUT WHERE BINGSEARCH_Q= 'Microsoft'


SELECT * FROM NEWS_VALUES WHERE BINGSEARCH_Q='White house'
SELECT * FROM NEWS_PROVIDER WHERE BINGSEARCH_Q = 'Halo'


SELECT * FROM VIDEOS_VALUES WHERE BINGSEARCH_Q='Master Chief'
SELECT * FROM VIDEOS_PUBLISHER WHERE BINGSEARCH_Q = 'Master Chief'

SELECT * FROM AUTOREST.RELATEDSEARCHES_VALUES WHERE BINGSEARCH_Q = 'Spartan 117'

SELECT * FROM AUTOREST.IMAGES_VALUES WHERE BINGSEARCH_Q='Master Chief'