{
	"StockIntraday":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Meta Data":{
			"1. Information":"VarChar(84)",
			"2. Symbol":"VarChar(64),#key",
			"3. Last Refreshed":"Timestamp(0)",
			"4. Interval":"VarChar(64)",
			"5. Output Size":"VarChar(64)",
			"6. Time Zone":"VarChar(64)"
		},
		"Time Series (5min){Timestamp(0)}":{
			"1. open":"Double",
			"2. high":"Double",
			"3. low":"Double",
			"4. close":"Double",
			"5. volume":"Integer"
		},
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TIME_SERIES_INTRADAY",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"5min",
			"#eq":"interval"
		},
		"outputsize":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"full",
			"#eq":"outputsize"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"StockDaily":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Meta Data":{
			"1. Information":"VarChar(73)",
			"2. Symbol":"VarChar(64),#key",
			"3. Last Refreshed":"Timestamp(0)",
			"4. Output Size":"VarChar(64)",
			"5. Time Zone":"VarChar(64)"
		},
		"Time Series (Daily){Date}":{
			"1. open":"Double",
			"2. high":"Double",
			"3. low":"Double",
			"4. close":"Double",
			"5. volume":"Integer"
		},
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TIME_SERIES_DAILY",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"outputsize":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"full",
			"#eq":"outputsize"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"StockDailyAdjusted":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Meta Data":{
			"1. Information":"VarChar(73)",
			"2. Symbol":"VarChar(64),#key",
			"3. Last Refreshed":"Timestamp(0)",
			"4. Output Size":"VarChar(64)",
			"5. Time Zone":"VarChar(64)"
		},
		"Time Series (Daily){Date}":{
			"1. open":"Double",
			"2. high":"Double",
			"3. low":"Double",
			"4. close":"Double",
			"5. adjusted close":"Double",
			"6. volume":"Integer",
			"7. dividend amount":"Double",
			"8. split coefficient":"Double"
		},
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TIME_SERIES_DAILY_ADJUSTED",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"outputsize":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"full",
			"#eq":"outputsize"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"StockWeekly":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Meta Data":{
			"1. Information":"VarChar(75)",
			"2. Symbol":"VarChar(64),#key",
			"3. Last Refreshed":"Timestamp(0)",
			"4. Time Zone":"VarChar(64)"
		},
		"Weekly Time Series{Date}":{
			"1. open":"Double",
			"2. high":"Double",
			"3. low":"Double",
			"4. close":"Double",
			"5. volume":"Integer"
		},
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TIME_SERIES_WEEKLY",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"StockWeeklyAdjusted":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Meta Data":{
			"1. Information":"VarChar(64),#key",
			"2. Symbol":"VarChar(64)",
			"3. Last Refreshed":"Timestamp(0)",
			"4. Time Zone":"VarChar(64)"
		},
		"Weekly Adjusted Time Series{Date}":{
			"1. open":"Double",
			"2. high":"Double",
			"3. low":"Double",
			"4. close":"Double",
			"5. adjusted close":"Double",
			"6. volume":"Integer",
			"7. dividend amount":"Double"
		},
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TIME_SERIES_WEEKLY_ADJUSTED",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"StockMonthly":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TIME_SERIES_MONTHLY",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"StockMonthlyAdjusted":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TIME_SERIES_MONTHLY_ADJUSTED",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"StockQuote":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"GLOBAL_QUOTE",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"StockSearchSymbol":{
		"#path":[
			"https://www.alphavantage.co/query /bestMatches"
		],
		"1. symbol":"VarChar(64),#key",
		"2. name":"VarChar(64)",
		"3. type":"VarChar(64)",
		"4. region":"VarChar(64)",
		"5. marketOpen":"VarChar(64)",
		"6. marketClose":"VarChar(64)",
		"7. timezone":"VarChar(64)",
		"8. currency":"VarChar(64)",
		"9. matchScore":"Double",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"SYMBOL_SEARCH",
			"#eq":"function"
		},
		"keywords":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"sony",
			"#eq":"keywords"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ExchangeRates":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"CURRENCY_EXCHANGE_RATE",
			"#eq":"function"
		},
		"from_currency":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"USD",
			"#eq":"from_currency"
		},
		"to_currency":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"JPY",
			"#eq":"to_currency"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ForexIntraday":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"FX_INTRADAY",
			"#eq":"function"
		},
		"from_symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"EUR",
			"#eq":"from_symbol"
		},
		"to_symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"USD",
			"#eq":"to_symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"5min",
			"#eq":"interval"
		},
		"outputsize":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"full",
			"#eq":"outputsize"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ForexDaily":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"FX_DAILY",
			"#eq":"function"
		},
		"from_symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"EUR",
			"#eq":"from_symbol"
		},
		"to_symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"USD",
			"#eq":"to_symbol"
		},
		"outputsize":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"full",
			"#eq":"outputsize"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ForexWeekly":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"FX_WEEKLY",
			"#eq":"function"
		},
		"from_symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"EUR",
			"#eq":"from_symbol"
		},
		"to_symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"USD",
			"#eq":"to_symbol"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ForexMonthly":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"FX_MONTHLY",
			"#eq":"function"
		},
		"from_symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"EUR",
			"#eq":"from_symbol"
		},
		"to_symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"USD",
			"#eq":"to_symbol"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"CryptoDaily":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"DIGITAL_CURRENCY_DAILY",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"BTC",
			"#eq":"symbol"
		},
		"market":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"CNY",
			"#eq":"market"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"CryptoWeekly":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"DIGITAL_CURRENCY_WEEKLY",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"BTC",
			"#eq":"symbol"
		},
		"market":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"CNY",
			"#eq":"market"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"CryptoMonthly":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"DIGITAL_CURRENCY_MONTHLY",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"BTC",
			"#eq":"symbol"
		},
		"market":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"CNY",
			"#eq":"market"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"SMA":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"SMA",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"EMA":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"EMA",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"WMA":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"WMA",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"DEMA":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"DEMA",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"TEMA":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TEMA",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"TRIMA":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TRIMA",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"KAMA":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"KAMA",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"MAMA":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MAMA",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"fastlimit":{
			"#type":"Double,#key",
			"#virtual":true,
			"#default":0.02,
			"#eq":"fastlimit"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"VWAP":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"VWAP",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"15min",
			"#eq":"interval"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"T3":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"T3",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"MACD":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MACD",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"MACDEXT":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MACDEXT",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"STOCH":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"STOCH",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"STOCHF":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"STOCHF",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"RSI":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"RSI",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"USDEUR",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"open",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"STOCHRSI":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"STOCHRSI",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"fastkperiod":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":6,
			"#eq":"fastkperiod"
		},
		"fastdmatype":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":1,
			"#eq":"fastdmatype"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"WILLR":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"WILLR",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ADX":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"ADX",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ADXR":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"ADXR",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"APO":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"APO",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"fastperiod":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"fastperiod"
		},
		"matype":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":1,
			"#eq":"matype"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"PPO":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"PPO",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"fastperiod":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"fastperiod"
		},
		"matype":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":1,
			"#eq":"matype"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"MOM":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MOM",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"BOP":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"BOP",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"CCI":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"CCI",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"CMO":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"CMO",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ROC":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"ROC",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ROCR":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"ROCR",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"AROON":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"AROON",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":14,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"AROONOSC":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"AROONOSC",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"MFI":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MFI",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"TRIX":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TRIX",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ULTOSC":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"ULTOSC",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"timeperiod1":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":8,
			"#eq":"timeperiod1"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"DX":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"DX",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"MINUS_DI":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MINUS_DI",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"PLUS_DI":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"PLUS_DI",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"MINUS_DM":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MINUS_DM",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"PLUS_DM":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"PLUS_DM",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"BBANDS":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"BBANDS",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":5,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"nbdevup":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":3,
			"#eq":"nbdevup"
		},
		"nbdevdn":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":3,
			"#eq":"nbdevdn"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"MIDPOINT":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MIDPOINT",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"MIDPRICE":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MIDPRICE",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":10,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"SAR":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"SAR",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"acceleration":{
			"#type":"Double,#key",
			"#virtual":true,
			"#default":0.05,
			"#eq":"acceleration"
		},
		"maximum":{
			"#type":"Double,#key",
			"#virtual":true,
			"#default":0.25,
			"#eq":"maximum"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"TRANGE":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"TRANGE",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ATR":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"ATR",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":14,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"NATR":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"NATR",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"time_period":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":14,
			"#eq":"time_period"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"AD":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"AD",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"ADOSC":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"ADOSC",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"fastperiod":{
			"#type":"Integer,#key",
			"#virtual":true,
			"#default":5,
			"#eq":"fastperiod"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"OBV":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"OBV",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"HT_TRENDLINE":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"HT_TRENDLINE",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"HT_SINE":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"HT_SINE",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"HT_TRENDMODE":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"HT_TRENDMODE",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"HT_DCPERIOD":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"HT_DCPERIOD",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"HT_DCPHASE":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"HT_DCPHASE",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"daily",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"HT_PHASOR":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"HT_PHASOR",
			"#eq":"function"
		},
		"symbol":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"MSFT",
			"#eq":"symbol"
		},
		"interval":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"weekly",
			"#eq":"interval"
		},
		"series_type":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"close",
			"#eq":"series_type"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	},
	"SECTOR":{
		"#path":[
			"https://www.alphavantage.co/query"
		],
		"Note":"VarChar(327)",
		"function":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"SECTOR",
			"#eq":"function"
		},
		"apikey":{
			"#type":"VarChar(64),#key",
			"#virtual":true,
			"#default":"demo",
			"#eq":"apikey"
		}
	}
}